/////////////////////////////////////////////////////////////////////////////
// Name:        catalog_volume.cpp
// Purpose:     
// Author:      
// Modified by: 
// Created:     31/12/2006 18:42:48
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 31/12/2006 18:42:48

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma implementation "catalog_volume.h"
#endif

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

////@begin includes
////@end includes

#include <wx/dir.h>
#include <wx/filename.h>
#include "catalog_volume.h"
#include "utils.h"
#include "data_interface/volumes.h"
#include "data_interface/paths.h"
#include "data_interface/files.h"

#ifdef __WXMSW__
#include "windows_specific.h"
#endif

////@begin XPM images
////@end XPM images

/*!
 * CDialogCatalogVolume type definition
 */

IMPLEMENT_DYNAMIC_CLASS( CDialogCatalogVolume, wxDialog )

/*!
 * CDialogCatalogVolume event table definition
 */

BEGIN_EVENT_TABLE( CDialogCatalogVolume, wxDialog )

////@begin CDialogCatalogVolume event table entries
    EVT_BUTTON( ID_GET_VOLUME_NAME, CDialogCatalogVolume::OnGetVolumeNameClick )

    EVT_BUTTON( ID_BUTTON_CATALOG, CDialogCatalogVolume::OnButtonCatalogClick )

////@end CDialogCatalogVolume event table entries

END_EVENT_TABLE()

/*!
 * CDialogCatalogVolume constructors
 */

CDialogCatalogVolume::CDialogCatalogVolume( )
{
    Init();
}

CDialogCatalogVolume::CDialogCatalogVolume( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
    Init();
    Create(parent, id, caption, pos, size, style);
}

/*!
 * Dialog creator
 */

bool CDialogCatalogVolume::Create( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
////@begin CDialogCatalogVolume creation
    SetExtraStyle(GetExtraStyle()|wxWS_EX_BLOCK_EVENTS);
    wxDialog::Create( parent, id, caption, pos, size, style );

    CreateControls();
    if (GetSizer())
    {
        GetSizer()->SetSizeHints(this);
    }
    Centre();
////@end CDialogCatalogVolume creation
    return true;
}

/*!
 * Member initialisation 
 */

void CDialogCatalogVolume::Init()
{
////@begin CDialogCatalogVolume member initialisation
////@end CDialogCatalogVolume member initialisation
}
/*!
 * Control creation for Dialog
 */

void CDialogCatalogVolume::CreateControls()
{    
////@begin CDialogCatalogVolume content construction
    // Generated by DialogBlocks, 01/01/2007 16:16:39 (unregistered)

    CDialogCatalogVolume* itemDialog1 = this;

    wxBoxSizer* itemBoxSizer2 = new wxBoxSizer(wxVERTICAL);
    itemDialog1->SetSizer(itemBoxSizer2);

    wxBoxSizer* itemBoxSizer3 = new wxBoxSizer(wxVERTICAL);
    itemBoxSizer2->Add(itemBoxSizer3, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5);

    wxStaticText* itemStaticText4 = new wxStaticText( itemDialog1, wxID_STATIC, _("Select the volume to catalog"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer3->Add(itemStaticText4, 0, wxALIGN_LEFT|wxALL, 5);

    wxGenericDirCtrl* itemGenericDirCtrl5 = new wxGenericDirCtrl( itemDialog1, ID_DIR_CTRL, _T(""), wxDefaultPosition, wxSize(100, 150), wxDIRCTRL_DIR_ONLY, _T("All files (*.*)|*.*"), 0 );
    itemBoxSizer3->Add(itemGenericDirCtrl5, 0, wxALIGN_LEFT|wxALL, 5);

    itemBoxSizer3->Add(5, 5, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5);

    wxStaticText* itemStaticText7 = new wxStaticText( itemDialog1, wxID_STATIC, _("Volume name"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer3->Add(itemStaticText7, 0, wxALIGN_LEFT|wxLEFT|wxRIGHT|wxTOP, 5);

    wxBoxSizer* itemBoxSizer8 = new wxBoxSizer(wxHORIZONTAL);
    itemBoxSizer3->Add(itemBoxSizer8, 0, wxALIGN_CENTER_HORIZONTAL|wxBOTTOM, 5);

    wxTextCtrl* itemTextCtrl9 = new wxTextCtrl( itemDialog1, ID_VOLUME_NAME, _T(""), wxDefaultPosition, wxSize(200, -1), 0 );
    itemBoxSizer8->Add(itemTextCtrl9, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxButton* itemButton10 = new wxButton( itemDialog1, ID_GET_VOLUME_NAME, _("Get volume name"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer8->Add(itemButton10, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxBoxSizer* itemBoxSizer11 = new wxBoxSizer(wxHORIZONTAL);
    itemBoxSizer3->Add(itemBoxSizer11, 0, wxGROW|wxTOP|wxBOTTOM, 5);

    wxButton* itemButton12 = new wxButton( itemDialog1, ID_BUTTON_CATALOG, _("Catalog"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer11->Add(itemButton12, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    itemBoxSizer11->Add(5, 5, 1, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxButton* itemButton14 = new wxButton( itemDialog1, wxID_CANCEL, _("&Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer11->Add(itemButton14, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

////@end CDialogCatalogVolume content construction
}

/*!
 * Should we show tooltips?
 */

bool CDialogCatalogVolume::ShowToolTips()
{
    return true;
}

/*!
 * Get bitmap resources
 */

wxBitmap CDialogCatalogVolume::GetBitmapResource( const wxString& name )
{
    // Bitmap retrieval
////@begin CDialogCatalogVolume bitmap retrieval
    wxUnusedVar(name);
    return wxNullBitmap;
////@end CDialogCatalogVolume bitmap retrieval
}

/*!
 * Get icon resources
 */

wxIcon CDialogCatalogVolume::GetIconResource( const wxString& name )
{
    // Icon retrieval
////@begin CDialogCatalogVolume icon retrieval
    wxUnusedVar(name);
    return wxNullIcon;
////@end CDialogCatalogVolume icon retrieval
}
/*!
 * wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_GET_VOLUME_NAME
 */

void CDialogCatalogVolume::OnGetVolumeNameClick( wxCommandEvent& event ) {
	event.Skip(false);	// to suppress a warning
#ifdef __WXMSW__
    wxGenericDirCtrl* gdc = (wxGenericDirCtrl*) FindWindow( ID_DIR_CTRL );
	wxString path = gdc->GetPath();
	if( !path.EndsWith(wxT("\\")) )
		path += wxT("\\");
	wxString vn = GetVolumeName( path );
	wxTextCtrl* vnc = (wxTextCtrl*) FindWindow( ID_VOLUME_NAME );
	vnc->SetValue( vn );
#endif
}


/*!
 * wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON_CATALOG
 */

void CDialogCatalogVolume::OnButtonCatalogClick( wxCommandEvent& event )
{
	event.Skip(false);	// to suppress a warning
	
	wxTextCtrl* vnc = (wxTextCtrl*) FindWindow( ID_VOLUME_NAME );
	wxString vn = vnc->GetValue();
	if( vn == "" ) {
		CUtils::MsgErr( _("The volume name is missing") );
		return;
	}

	{
		// to avoid name conflict	
		CVolumes vol;
		vol.VolumeName = vn;
		if( vol.NameExists() ) {
			CUtils::MsgErr( _("This volume name is already present in the database") );
			return;
		}
	}

	wxCursor curCursor = GetCursor();
	SetCursor(wxCursor(wxCURSOR_WAIT));

	// starts a transaction
	CBaseDB* db = CBaseDB::GetDatabase();
	db->TransactionStart();

	wxGenericDirCtrl* gdc = (wxGenericDirCtrl*) FindWindow( ID_DIR_CTRL );
	wxString path = gdc->GetPath();
	wxFileName dirName( path, wxEmptyString );

	// writes the volume row
	CVolumes vol;
	vol.VolumeName = vn;
	vol.DbInsert();

	// catalogs the folders
	CNullableLong FatherID;
	FatherID.SetNull(true);
	CatalogSingleFolder( db, path, vol.VolumeID, FatherID );

	// commits the transaction
	db->TransactionCommit();

	vnc->SetValue( wxT("") );
	SetCursor(curCursor);
}


void CDialogCatalogVolume::CatalogSingleFolder( CBaseDB* db, wxString path, long VolumeID, CNullableLong& FatherID  ) {
	wxString fileName;

	// writes the path row
	wxFileName dirName( path, wxEmptyString );
	CPaths pth;
	pth.VolumeID = VolumeID;
	pth.PathName = dirName.GetPath(0);
	pth.FatherID = FatherID;
	pth.DbInsert();

	// reads all file names
	wxDir dir(path);
	bool cont = dir.GetFirst(&fileName, wxT("*.*"), wxDIR_FILES );
	while( cont ) {
		// stores the file row
		wxFileName fn( path, fileName );
		CFiles file;
		file.FileName = fileName;
		file.FileExt = fn.GetExt();
		file.DateTime = fn.GetModificationTime();
		file.FileSize = fn.GetSize();
		file.PathID = pth.PathID;
		file.IsFolder = false;
		file.DbInsert();

		cont = dir.GetNext(&fileName);
	}

	// now reads all the subfolders
	cont = dir.GetFirst(&fileName, wxT("*.*"), wxDIR_DIRS );
	while( cont ) {
		wxFileName dirName( path, wxEmptyString );
		dirName.AppendDir( fileName );

		// stores the folder as a file to simplify data retrieval
		CFiles file;
		file.FileName = fileName;
		file.FileExt = "";
		file.DateTime = dirName.GetModificationTime();
		file.FileSize = 0;
		file.PathID = pth.PathID;
		file.IsFolder = true;
		file.DbInsert();

		CatalogSingleFolder( db, dirName.GetPath(), VolumeID, pth.PathID );
		cont = dir.GetNext(&fileName);
	}

}