/*
	This file is part of VVV (Virtual Volumes View)

	Copyright (C) 2007, the VVV Development team

	Author: Fulvio Senore

    VVV is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    VVV is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with VVV; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*/

/////////////////////////////////////////////////////////////////////////////
// Name:        mainframe.cpp
// Purpose:     
// Author:      
// Modified by: 
// Created:     29/12/2006 12:41:00
// RCS-ID:      
// Copyright:   
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 29/12/2006 12:41:00

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma implementation "mainframe.h"
#endif

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

////@begin includes
#include "catalog_volume.h"
////@end includes

#include "wx/textdlg.h"
#include "wx/filename.h"
#include "wx/config.h"
#include "wx/utils.h"
#include "wx/aboutdlg.h"
#include "wx/stdpaths.h"
#include "wx/textfile.h"
#include "wx/busyinfo.h"
#include "vvv.h"
#include "mainframe.h"
#include "data_interface/data_error.h"
#include "mytreeitemdata.h"
#include "mylistitemdata.h"
#include "volume_description.h"

////@begin XPM images
#include "graphics/vvv32.xpm"
#include "graphics/tlb_new.xpm"
#include "graphics/tlb_open.xpm"
#include "graphics/tlb_catalog.xpm"
#include "graphics/tlb_up.xpm"
#include "graphics/tlb_physical.xpm"
#include "graphics/tlb_virtual.xpm"
#include "graphics/tlb_search.xpm"
////@end XPM images

#include "graphics/folder_closed.xpm"
#include "graphics/folder_opened.xpm"
#include "graphics/removable.xpm"
#include "graphics/deffile.xpm"

// column used to sort the listview
int m_ListViewSortColumn;
// sorting order
bool m_ListViewSortAscending;

int wxCALLBACK ListControlCompareFunction( long item1, long item2, long WXUNUSED(sortData) ) {
	int retVal = 0;

	MyListItemData* itemData1 = (MyListItemData*) item1;
	MyListItemData* itemData2 = (MyListItemData*) item2;

	// make sure that folders are always listed before files
	if( itemData1->IsFolder() && !itemData2->IsFolder() ) return -1;
	if( !itemData1->IsFolder() && itemData2->IsFolder() ) return 1;

	switch( m_ListViewSortColumn ) {
		case 0:
			// filename
			if( m_ListViewSortAscending )
				retVal = wxStricmp( itemData1->GetName(), itemData2->GetName() );
			else
				retVal = wxStricmp( itemData2->GetName(), itemData1->GetName() );
			break;
		case 1:
			// size
			if( itemData1->GetSize() == itemData2->GetSize() )
				retVal = 0;
			else {
				if( m_ListViewSortAscending )
					retVal = (itemData1->GetSize() < itemData2->GetSize() ? -1 : 1);
				else
					retVal = (itemData1->GetSize() > itemData2->GetSize() ? -1 : 1);
			}
			break;
		case 2:
			// extension
			if( m_ListViewSortAscending )
				retVal = wxStricmp( itemData1->GetExt(), itemData2->GetExt() );
			else
				retVal = wxStricmp( itemData2->GetExt(), itemData1->GetExt() );
			if( retVal == 0 ) {
				if( m_ListViewSortAscending )
					retVal = wxStricmp( itemData1->GetName(), itemData2->GetName() );
				else
					retVal = wxStricmp( itemData2->GetName(), itemData1->GetName() );
			}
			break;
		case 3:
			// datetime
			if( itemData1->GetDateTime() == itemData2->GetDateTime() )
				retVal = 0;
			else {
				if( m_ListViewSortAscending )
					retVal = (itemData1->GetDateTime() < itemData2->GetDateTime() ? -1 : 1);
				else
					retVal = (itemData1->GetDateTime() > itemData2->GetDateTime() ? -1 : 1);
			}
			break;
		case 4:
			// full physical path
			if( m_ListViewSortAscending )
				retVal = wxStricmp( itemData1->GetFullPhysicalPath(), itemData2->GetFullPhysicalPath() );
			else
				retVal = wxStricmp( itemData2->GetFullPhysicalPath(), itemData1->GetFullPhysicalPath() );
			if( retVal == 0 ) {
				if( m_ListViewSortAscending )
					retVal = wxStricmp( itemData1->GetName(), itemData2->GetName() );
				else
					retVal = wxStricmp( itemData2->GetName(), itemData1->GetName() );
			}
			break;
	}
	return retVal;
}


/*!
 * CMainFrame type definition
 */

IMPLEMENT_CLASS( CMainFrame, wxFrame )

/*!
 * CMainFrame event table definition
 */

BEGIN_EVENT_TABLE( CMainFrame, wxFrame )

////@begin CMainFrame event table entries
    EVT_MENU( wxID_NEW, CMainFrame::OnNEWClick )

    EVT_MENU( wxID_OPEN, CMainFrame::OnOPENClick )

    EVT_MENU( wxID_EXIT, CMainFrame::OnEXITClick )

    EVT_MENU( ID_ADD_VIRTUAL_FOLDER, CMainFrame::OnAddVirtualFolderClick )
    EVT_UPDATE_UI( ID_ADD_VIRTUAL_FOLDER, CMainFrame::OnAddVirtualFolderUpdate )

    EVT_MENU( ID_EDIT_VOLUME_DESCRIPTION, CMainFrame::OnEditVolumeDescriptionClick )
    EVT_UPDATE_UI( ID_EDIT_VOLUME_DESCRIPTION, CMainFrame::OnEditVolumeDescriptionUpdate )

    EVT_MENU( ID_RENAME_VOLUME, CMainFrame::OnRenameVolumeClick )
    EVT_UPDATE_UI( ID_RENAME_VOLUME, CMainFrame::OnRenameVolumeUpdate )

    EVT_MENU( ID_DELETE_VOLUME, CMainFrame::OnDeleteVolumeClick )
    EVT_UPDATE_UI( ID_DELETE_VOLUME, CMainFrame::OnDeleteVolumeUpdate )

    EVT_MENU( ID_NEW_VIRTUAL_ROOT_FOLDER, CMainFrame::OnNewVirtualRootFolderClick )
    EVT_UPDATE_UI( ID_NEW_VIRTUAL_ROOT_FOLDER, CMainFrame::OnNewVirtualRootFolderUpdate )

    EVT_MENU( ID_NEW_VIRTUAL_SUBFOLDER, CMainFrame::OnNewVirtualSubfolderClick )
    EVT_UPDATE_UI( ID_NEW_VIRTUAL_SUBFOLDER, CMainFrame::OnNewVirtualSubfolderUpdate )

    EVT_MENU( ID_RENAME_VIRTUAL_FOLDER, CMainFrame::OnRenameVirtualFolderClick )
    EVT_UPDATE_UI( ID_RENAME_VIRTUAL_FOLDER, CMainFrame::OnRenameVirtualFolderUpdate )

    EVT_MENU( ID_DELETE_VIRTUAL_FOLDER, CMainFrame::OnDeleteVirtualFolderClick )
    EVT_UPDATE_UI( ID_DELETE_VIRTUAL_FOLDER, CMainFrame::OnDeleteVirtualFolderUpdate )

    EVT_MENU( ID_CATALOG_VOLUME, CMainFrame::OnCatalogVolumeClick )
    EVT_UPDATE_UI( ID_CATALOG_VOLUME, CMainFrame::OnCatalogVolumeUpdate )

    EVT_MENU( ID_VIEW_PHYSICAL, CMainFrame::OnViewPhysicalClick )
    EVT_UPDATE_UI( ID_VIEW_PHYSICAL, CMainFrame::OnViewPhysicalUpdate )

    EVT_MENU( ID_VIEW_VIRTUAL, CMainFrame::OnViewVirtualClick )
    EVT_UPDATE_UI( ID_VIEW_VIRTUAL, CMainFrame::OnViewVirtualUpdate )

    EVT_MENU( ID_VIEW_SEARCH, CMainFrame::OnViewSearchClick )
    EVT_UPDATE_UI( ID_VIEW_SEARCH, CMainFrame::OnViewSearchUpdate )

    EVT_MENU( ID_UP_ONE_FOLDER, CMainFrame::OnUpOneFolderClick )
    EVT_UPDATE_UI( ID_UP_ONE_FOLDER, CMainFrame::OnUpOneFolderUpdate )

    EVT_MENU( ID_VIEW_TOOLBAR, CMainFrame::OnViewToolbarClick )

    EVT_MENU( ID_VIEW_STATUS_BAR, CMainFrame::OnViewStatusBarClick )

    EVT_MENU( wxID_ABOUT, CMainFrame::OnABOUTClick )

    EVT_TREE_SEL_CHANGED( ID_TREE_CONTROL, CMainFrame::OnTreeControlSelChanged )
    EVT_TREE_ITEM_EXPANDING( ID_TREE_CONTROL, CMainFrame::OnTreeControlItemExpanding )
    EVT_TREE_ITEM_MENU( ID_TREE_CONTROL, CMainFrame::OnTreeControlItemMenu )

    EVT_LIST_ITEM_ACTIVATED( ID_LIST_CONTROL, CMainFrame::OnListControlItemActivated )
    EVT_LIST_COL_CLICK( ID_LIST_CONTROL, CMainFrame::OnListControlColLeftClick )

////@end CMainFrame event table entries

    EVT_TREE_SEL_CHANGED( ID_TREE_CONTROL_VIRTUAL, CMainFrame::OnTreeControlVirtualSelChanged )
    EVT_TREE_ITEM_EXPANDING( ID_TREE_CONTROL_VIRTUAL, CMainFrame::OnTreeControlVirtualItemExpanding )
    EVT_TREE_ITEM_MENU( ID_TREE_CONTROL_VIRTUAL, CMainFrame::OnTreeControlVirtualItemMenu )

	EVT_MENU_RANGE( wxID_FILE1, wxID_FILE9, CMainFrame::OnMRUFile)

    EVT_BUTTON( ID_BUTTON_SEARCH, CMainFrame::OnButtonSearchClick )

END_EVENT_TABLE()

/*!
 * CMainFrame constructors
 */

CMainFrame::CMainFrame( )
{
    Init();
}

CMainFrame::CMainFrame( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
//	wxIcon ico(removable_xpm);
    Init();
    Create( parent, id, caption, pos, size, style );
}

/*!
 * Prova creator
 */

bool CMainFrame::Create( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
////@begin CMainFrame creation
    wxFrame::Create( parent, id, caption, pos, size, style );

    CreateControls();
    SetIcon(GetIconResource(wxT("graphics/vvv32.xpm")));
    Centre();
////@end CMainFrame creation

	// reads the frame position from the config object
	wxConfigBase *pConfig = wxConfigBase::Get();
	pConfig->SetPath(wxT("/Mainframe/Layout"));
	int x = pConfig->Read(wxT("x"), 50),
		y = pConfig->Read(wxT("y"), 50),
		w = pConfig->Read(wxT("w"), 600),
		h = pConfig->Read(wxT("h"), 400);
	Move(x, y);
	SetClientSize(w, h);
	bool FrameMaximized;
	pConfig->Read( wxT("Maximized"), &FrameMaximized, false );
	if( FrameMaximized ) Maximize(true);

	// reads the splitter sash position
	wxSplitterWindow* sw = GetSplitterWindow();
	sw->SetSashPosition( pConfig->Read(wxT("SashPosition"), 200) );

	// reads the MRU files list
	m_fileHistory->Load( *pConfig );

	// reads the listview columns width
	pConfig->SetPath(wxT("/Mainframe/Layout/ListViewPhysical"));
	m_ListviewColWidthPhysical[0] = pConfig->Read(wxT("cw0"), 200);
	m_ListviewColWidthPhysical[1] = pConfig->Read(wxT("cw1"), 100);
	m_ListviewColWidthPhysical[2] = pConfig->Read(wxT("cw2"), 100);
	m_ListviewColWidthPhysical[3] = pConfig->Read(wxT("cw3"), 200);
	pConfig->SetPath(wxT("/Mainframe/Layout/ListViewVirtual"));
	m_ListviewColWidthVirtual[0] = pConfig->Read(wxT("cw0"), 200);
	m_ListviewColWidthVirtual[1] = pConfig->Read(wxT("cw1"), 100);
	m_ListviewColWidthVirtual[2] = pConfig->Read(wxT("cw2"), 100);
	m_ListviewColWidthVirtual[3] = pConfig->Read(wxT("cw3"), 200);
	m_ListviewColWidthVirtual[4] = pConfig->Read(wxT("cw4"), 200);

	CreateListControlHeaders();

	// checks to see if a catalog name has been passed in the command line
	wxString catalogName = wxGetApp().GetParameterCatalog();
	if( !catalogName.empty() ) {
		if( !wxFileName::FileExists(catalogName) ) {
			CUtils::MsgErr( "This catalog file does not exist:\n\n" + catalogName );
			catalogName = "";
		}
	}
	if( !catalogName.empty() )
		OpenDatabase( catalogName, CUtils::GetExpectedDatabaseVersion() );

	return true;
}

/*!
 * Member initialisation 
 */

void CMainFrame::Init()
{
//	wxIcon ico(removable_xpm);
////@begin CMainFrame member initialisation
    m_Toolbar = NULL;
    m_fileMenu = NULL;
    m_StatusBar = NULL;
////@end CMainFrame member initialisation
	m_ChooseVirtualFolderDialog = NULL;

    m_SearchPanel = NULL;
    m_FilenameRadioBox = NULL;
    m_SearchFileName = NULL;
    m_SearchExtension = NULL;
    m_SearchRadioBox = NULL;
    m_SearchButton = NULL;

	m_fileHistory = new wxFileHistory();
	
	m_CurrentView = Physical;	// let's start with the physical view

	m_ListViewSortColumn = 0;
	m_ListViewSortAscending = true;

	nPhysicalFiles = nVirtualFiles = nSearchFiles = 0;
	sizePhysicalFiles = sizeVirtualFiles =  sizeSearchFiles = 0;
}
/*!
 * Control creation for Prova
 */

void CMainFrame::CreateControls()
{    
////@begin CMainFrame content construction
    CMainFrame* itemFrame1 = this;

    wxMenuBar* menuBar = new wxMenuBar;
    m_fileMenu = new wxMenu;
    m_fileMenu->Append(wxID_NEW, _("New..."), _T(""), wxITEM_NORMAL);
    m_fileMenu->Append(wxID_OPEN, _("Open..."), _T(""), wxITEM_NORMAL);
    m_fileMenu->AppendSeparator();
    m_fileMenu->Append(wxID_EXIT, _("Exit"), _T(""), wxITEM_NORMAL);
    menuBar->Append(m_fileMenu, _("File"));
    wxMenu* itemMenu17 = new wxMenu;
    itemMenu17->Append(ID_ADD_VIRTUAL_FOLDER, _("Add To Virtual Folder..."), _T(""), wxITEM_NORMAL);
    itemMenu17->AppendSeparator();
    itemMenu17->Append(ID_EDIT_VOLUME_DESCRIPTION, _("Volume Description..."), _T(""), wxITEM_NORMAL);
    itemMenu17->Append(ID_RENAME_VOLUME, _("Rename Volume..."), _T(""), wxITEM_NORMAL);
    itemMenu17->Append(ID_DELETE_VOLUME, _("Delete Volume"), _T(""), wxITEM_NORMAL);
    itemMenu17->AppendSeparator();
    itemMenu17->Append(ID_NEW_VIRTUAL_ROOT_FOLDER, _("New Virtual Root Folder..."), _T(""), wxITEM_NORMAL);
    itemMenu17->Append(ID_NEW_VIRTUAL_SUBFOLDER, _("New Virtual Subfolder..."), _T(""), wxITEM_NORMAL);
    itemMenu17->Append(ID_RENAME_VIRTUAL_FOLDER, _("Rename Virtual Folder..."), _T(""), wxITEM_NORMAL);
    itemMenu17->Append(ID_DELETE_VIRTUAL_FOLDER, _("Delete Virtual Folder"), _T(""), wxITEM_NORMAL);
    menuBar->Append(itemMenu17, _("Edit"));
    wxMenu* itemMenu28 = new wxMenu;
    itemMenu28->Append(ID_CATALOG_VOLUME, _("Catalog Volume..."), _T(""), wxITEM_NORMAL);
    menuBar->Append(itemMenu28, _("Volumes"));
    wxMenu* itemMenu30 = new wxMenu;
    itemMenu30->Append(ID_VIEW_PHYSICAL, _("Physical View"), _T(""), wxITEM_RADIO);
    itemMenu30->Check(ID_VIEW_PHYSICAL, true);
    itemMenu30->Append(ID_VIEW_VIRTUAL, _("Virtual View"), _T(""), wxITEM_RADIO);
    itemMenu30->Append(ID_VIEW_SEARCH, _("Search View"), _T(""), wxITEM_RADIO);
    itemMenu30->AppendSeparator();
    itemMenu30->Append(ID_UP_ONE_FOLDER, _("Go Up One Level"), _T(""), wxITEM_NORMAL);
    itemMenu30->AppendSeparator();
    itemMenu30->Append(ID_VIEW_TOOLBAR, _("Toolbar"), _T(""), wxITEM_CHECK);
    itemMenu30->Check(ID_VIEW_TOOLBAR, true);
    itemMenu30->Append(ID_VIEW_STATUS_BAR, _("Status Bar"), _T(""), wxITEM_CHECK);
    itemMenu30->Check(ID_VIEW_STATUS_BAR, true);
    menuBar->Append(itemMenu30, _("View"));
    wxMenu* itemMenu39 = new wxMenu;
    itemMenu39->Append(wxID_ABOUT, _("About VVV..."), _T(""), wxITEM_NORMAL);
    menuBar->Append(itemMenu39, _("Help"));
    itemFrame1->SetMenuBar(menuBar);

    m_Toolbar = CreateToolBar( wxTB_FLAT|wxTB_HORIZONTAL|wxTB_TEXT, ID_TOOLBAR1 );
    m_Toolbar->SetToolBitmapSize(wxSize(16, 16));
    wxBitmap itemtool3Bitmap(itemFrame1->GetBitmapResource(wxT("graphics/tlb_new.xpm")));
    wxBitmap itemtool3BitmapDisabled;
    m_Toolbar->AddTool(wxID_NEW, _("New"), itemtool3Bitmap, itemtool3BitmapDisabled, wxITEM_NORMAL, _("Create a new catalog"), wxEmptyString);
    wxBitmap itemtool4Bitmap(itemFrame1->GetBitmapResource(wxT("graphics/tlb_open.xpm")));
    wxBitmap itemtool4BitmapDisabled;
    m_Toolbar->AddTool(wxID_OPEN, _("Open"), itemtool4Bitmap, itemtool4BitmapDisabled, wxITEM_NORMAL, _("Open an existing catalog"), wxEmptyString);
    wxBitmap itemtool5Bitmap(itemFrame1->GetBitmapResource(wxT("graphics/tlb_catalog.xpm")));
    wxBitmap itemtool5BitmapDisabled;
    m_Toolbar->AddTool(ID_CATALOG_VOLUME, _("Catalog"), itemtool5Bitmap, itemtool5BitmapDisabled, wxITEM_NORMAL, _("Catalog a new volume"), wxEmptyString);
    wxBitmap itemtool6Bitmap(itemFrame1->GetBitmapResource(wxT("graphics/tlb_up.xpm")));
    wxBitmap itemtool6BitmapDisabled;
    m_Toolbar->AddTool(ID_UP_ONE_FOLDER, _("Up"), itemtool6Bitmap, itemtool6BitmapDisabled, wxITEM_NORMAL, _("Move up one level"), wxEmptyString);
    m_Toolbar->AddSeparator();
    wxBitmap itemtool8Bitmap(itemFrame1->GetBitmapResource(wxT("graphics/tlb_physical.xpm")));
    wxBitmap itemtool8BitmapDisabled;
    m_Toolbar->AddTool(ID_VIEW_PHYSICAL, _("Physical"), itemtool8Bitmap, itemtool8BitmapDisabled, wxITEM_RADIO, _("Show the physical view"), wxEmptyString);
    wxBitmap itemtool9Bitmap(itemFrame1->GetBitmapResource(wxT("graphics/tlb_virtual.xpm")));
    wxBitmap itemtool9BitmapDisabled;
    m_Toolbar->AddTool(ID_VIEW_VIRTUAL, _("Virtual"), itemtool9Bitmap, itemtool9BitmapDisabled, wxITEM_RADIO, _("Show the virtual view"), wxEmptyString);
    wxBitmap itemtool10Bitmap(itemFrame1->GetBitmapResource(wxT("graphics/tlb_search.xpm")));
    wxBitmap itemtool10BitmapDisabled;
    m_Toolbar->AddTool(ID_VIEW_SEARCH, _("Search"), itemtool10Bitmap, itemtool10BitmapDisabled, wxITEM_RADIO, _("Show the search view"), wxEmptyString);
    m_Toolbar->Realize();
    itemFrame1->SetToolBar(m_Toolbar);

    m_StatusBar = new wxStatusBar( itemFrame1, ID_STATUSBAR1, wxST_SIZEGRIP );
    m_StatusBar->SetFieldsCount(4);
    int m_StatusBarWidths[4];
    m_StatusBarWidths[0] = 300;
    m_StatusBarWidths[1] = 150;
    m_StatusBarWidths[2] = 150;
    m_StatusBarWidths[3] = -1;
    m_StatusBar->SetStatusWidths(4, m_StatusBarWidths);
    itemFrame1->SetStatusBar(m_StatusBar);

    wxSplitterWindow* itemSplitterWindow42 = new wxSplitterWindow( itemFrame1, ID_SPLITTERWINDOW1, wxDefaultPosition, wxSize(100, 100), wxSP_3DBORDER|wxSP_3DSASH|wxSP_NO_XP_THEME|wxNO_BORDER );
    itemSplitterWindow42->SetMinimumPaneSize(0);

    wxTreeCtrl* itemTreeCtrl43 = new wxTreeCtrl( itemSplitterWindow42, ID_TREE_CONTROL, wxDefaultPosition, wxSize(100, 100), wxTR_HAS_BUTTONS |wxTR_HIDE_ROOT|wxTR_SINGLE|wxNO_BORDER|wxTR_DEFAULT_STYLE );

    wxListCtrl* itemListCtrl44 = new wxListCtrl( itemSplitterWindow42, ID_LIST_CONTROL, wxDefaultPosition, wxSize(100, 100), wxLC_REPORT|wxNO_BORDER );

    itemSplitterWindow42->SplitVertically(itemTreeCtrl43, itemListCtrl44, 50);

////@end CMainFrame content construction

	// creates the tree control used to show virtual folders
	// this control must be created in the same way as the tree control created above
	wxSplitterWindow* sw = (wxSplitterWindow*) FindWindow( ID_SPLITTERWINDOW1 );
	wxTreeCtrl* itemTreeCtrlVirtual = new wxTreeCtrl( sw, ID_TREE_CONTROL_VIRTUAL, wxDefaultPosition, wxSize(100, 100), wxTR_HAS_BUTTONS |wxTR_HIDE_ROOT|wxTR_SINGLE|wxNO_BORDER|wxTR_DEFAULT_STYLE );
	itemTreeCtrlVirtual->Show( false );

	// stores a pointer to some window components for later use
	m_splitterWindow = sw;
	m_treePhysicalCtl = (wxTreeCtrl*) FindWindow( ID_TREE_CONTROL );
	m_treeVirtualCtl = (wxTreeCtrl*) FindWindow( ID_TREE_CONTROL_VIRTUAL );
	m_listCtl = (wxListCtrl*) FindWindow( ID_LIST_CONTROL );

	// creates the search panel
	{
		m_SearchPanel = new wxPanel( m_splitterWindow, ID_SEARCH_PANEL, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL );

		wxBoxSizer* itemBoxSizer3 = new wxBoxSizer(wxVERTICAL);
		m_SearchPanel->SetSizer(itemBoxSizer3);

		wxArrayString m_FilenameRadioBoxStrings;
		m_FilenameRadioBoxStrings.Add(_("Is &equal to:"));
		m_FilenameRadioBoxStrings.Add(_("S&tarts with:"));
		m_FilenameRadioBoxStrings.Add(_("&Contains:"));
		m_FilenameRadioBox = new wxRadioBox( m_SearchPanel, ID_RADIOBOX_FILENAME, _("File name"), wxDefaultPosition, wxDefaultSize, m_FilenameRadioBoxStrings, 1, wxRA_SPECIFY_COLS );
		m_FilenameRadioBox->SetSelection(0);
		itemBoxSizer3->Add(m_FilenameRadioBox, 0, wxALIGN_LEFT|wxALL, 5);

		m_SearchFileName = new wxTextCtrl( m_SearchPanel, ID_SEARCH_FILE_NAME, _T(""), wxDefaultPosition, wxSize(120, -1), 0 );
		itemBoxSizer3->Add(m_SearchFileName, 0, wxALIGN_LEFT|wxALL, 5);

		itemBoxSizer3->Add(5, 3, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5);

		wxStaticText* itemStaticText7 = new wxStaticText( m_SearchPanel, wxID_STATIC, _("E&xtension:"), wxDefaultPosition, wxDefaultSize, 0 );
		itemBoxSizer3->Add(itemStaticText7, 0, wxALIGN_LEFT|wxALL, 5);

		m_SearchExtension = new wxTextCtrl( m_SearchPanel, ID_SEARCH_EXTENSION, _T(""), wxDefaultPosition, wxSize(60, -1), 0 );
		itemBoxSizer3->Add(m_SearchExtension, 0, wxALIGN_LEFT|wxALL, 5);

		itemBoxSizer3->Add(5, 3, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5);

		wxArrayString m_SearchRadioBoxStrings;
		m_SearchRadioBoxStrings.Add(_("&All physical volumes"));
		m_SearchRadioBoxStrings.Add(_("Selected &physical folder"));
		m_SearchRadioBoxStrings.Add(_("Selected &virtual folder"));
		m_SearchRadioBox = new wxRadioBox( m_SearchPanel, ID_RADIOBOX_SEARCH, _("Search"), wxDefaultPosition, wxDefaultSize, m_SearchRadioBoxStrings, 1, wxRA_SPECIFY_COLS );
		m_SearchRadioBox->SetSelection(0);
		itemBoxSizer3->Add(m_SearchRadioBox, 0, wxALIGN_LEFT|wxALL, 5);

		itemBoxSizer3->Add(5, 3, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5);

		m_SearchButton = new wxButton( m_SearchPanel, ID_BUTTON_SEARCH, _("&Search"), wxDefaultPosition, wxDefaultSize, 0 );
		m_SearchButton->SetDefault();
		itemBoxSizer3->Add(m_SearchButton, 0, wxALIGN_LEFT|wxALL, 5);

		m_SearchPanel->Show( false );
	}

	// associates the MRU files list
	m_fileHistory->UseMenu( m_fileMenu );

}


/*!
 * Should we show tooltips?
 */

bool CMainFrame::ShowToolTips()
{
    return true;
}

/*!
 * Get bitmap resources
 */

wxBitmap CMainFrame::GetBitmapResource( const wxString& name )
{
    // Bitmap retrieval
////@begin CMainFrame bitmap retrieval
    wxUnusedVar(name);
    if (name == _T("graphics/tlb_new.xpm"))
    {
        wxBitmap bitmap(tlb_new_xpm);
        return bitmap;
    }
    else if (name == _T("graphics/tlb_open.xpm"))
    {
        wxBitmap bitmap(tlb_open_xpm);
        return bitmap;
    }
    else if (name == _T("graphics/tlb_catalog.xpm"))
    {
        wxBitmap bitmap(tlb_catalog_xpm);
        return bitmap;
    }
    else if (name == _T("graphics/tlb_up.xpm"))
    {
        wxBitmap bitmap(tlb_up_xpm);
        return bitmap;
    }
    else if (name == _T("graphics/tlb_physical.xpm"))
    {
        wxBitmap bitmap(tlb_physical_xpm);
        return bitmap;
    }
    else if (name == _T("graphics/tlb_virtual.xpm"))
    {
        wxBitmap bitmap(tlb_virtual_xpm);
        return bitmap;
    }
    else if (name == _T("graphics/tlb_search.xpm"))
    {
        wxBitmap bitmap(tlb_search_xpm);
        return bitmap;
    }
    return wxNullBitmap;
////@end CMainFrame bitmap retrieval
}

/*!
 * Get icon resources
 */

wxIcon CMainFrame::GetIconResource( const wxString& name )
{
    // Icon retrieval
////@begin CMainFrame icon retrieval
    wxUnusedVar(name);
    if (name == _T("graphics/vvv32.xpm"))
    {
        wxIcon icon(vvv32_xpm);
        return icon;
    }
    return wxNullIcon;
////@end CMainFrame icon retrieval
}
/*!
 * wxEVT_COMMAND_MENU_SELECTED event handler for ID_CATALOG_VOLUME
 */

void CMainFrame::OnCatalogVolumeClick( wxCommandEvent& WXUNUSED(event) )
{
    CDialogCatalogVolume* window = new CDialogCatalogVolume(this, ID_DIALOG_CATALOG_VOLUME, _("Catalog volume"));
    window->ShowModal();
	LoadTreeControl();
}


void CMainFrame::LoadTreeControl(void) {

	wxTreeCtrl* tctl = GetTreePhysicalControl();
	wxImageList* iml = new wxImageList( 16, 16 );
	wxIcon ico(removable_xpm);
	iml->Add(ico);
//	iml->Add(wxIcon(removable_xpm));
	iml->Add(wxIcon(folder_closed_xpm));
	iml->Add(wxIcon(folder_opened_xpm));
	tctl->AssignImageList( iml );

	tctl->DeleteAllItems();

	// adds a root item that will not be visible
	wxTreeItemId rootID = tctl->AddRoot( wxT("Root") );

	CVolumes vol;
	vol.DBStartQueryListVolumes();
	while( !vol.IsEOF() ) {
		LoadVolumeInTreeControl( vol, tctl, rootID );
		vol.DBNextRow();
	}
}


void CMainFrame::LoadVolumeInTreeControl( CVolumes vol, wxTreeCtrl* tctl, wxTreeItemId rootID ) {

	// first retrieves the id of the root folder
	long rootPathID = -1;
	CPaths pth;
	CNullableLong nl;
	nl.SetNull(true);
	pth.DBStartQueryListPaths( vol.VolumeID, nl );
	while( !pth.IsEOF() ) {
		// this query should return only one row
		rootPathID = pth.PathID;
		pth.DBNextRow();
	}

	// appends the volume item
	wxTreeItemId volumeID = tctl->AppendItem( rootID, CreateVolumeLabel(vol.VolumeName, vol.VolumeDescription), 0, 0, 
							new MyTreeItemData(vol.VolumeName, vol.VolumeID, rootPathID, true, vol.VolumeDescription) );

	// appends the first level of subfolders

	// now retrieves the subfolders
	nl = rootPathID;
	pth.DBStartQueryListPaths( vol.VolumeID, nl );
	while( !pth.IsEOF() ) {
		wxString name = pth.PathName;
		// adds the folder to the tree
		wxTreeItemId itemID = tctl->AppendItem( volumeID, name, 1, 2, 
							new MyTreeItemData(name, vol.VolumeID, pth.PathID, false, "") );
		// sets the expanded images
		tctl->SetItemImage( itemID, 1, wxTreeItemIcon_Expanded );
		tctl->SetItemImage( itemID, 2, wxTreeItemIcon_SelectedExpanded );
		// adds the subfolders
		LoadFolderInTreeControl( vol.VolumeID, tctl, itemID, pth.PathID );

		pth.DBNextRow();
	}

}


void CMainFrame::LoadFolderInTreeControl( long VolumeID, wxTreeCtrl* tctl, wxTreeItemId fatherTreeID, long fatherID ) {

	CPaths pth;
	pth.DBStartQueryListPaths( VolumeID, fatherID );
	while( !pth.IsEOF() ) {
		wxString name = pth.PathName;
		name = name.AfterLast( wxFileName::GetPathSeparator() );
		// adds the folder to the tree
		wxTreeItemId itemID = tctl->AppendItem( fatherTreeID, name, 1, 2, 
							new MyTreeItemData(name, VolumeID, pth.PathID, false, "") );
		// sets the expanded images
		tctl->SetItemImage( itemID, 1, wxTreeItemIcon_Expanded );
		tctl->SetItemImage( itemID, 2, wxTreeItemIcon_SelectedExpanded );

		pth.DBNextRow();
	}
}

void CMainFrame::LoadVirtualTreeControl(void) {

	wxTreeCtrl* tctl = GetTreeVirtualControl();
	wxImageList* iml = new wxImageList( 16, 16 );
	iml->Add(wxIcon(removable_xpm));
	iml->Add(wxIcon(folder_closed_xpm));
	iml->Add(wxIcon(folder_opened_xpm));
	tctl->AssignImageList( iml );

	tctl->DeleteAllItems();

	// adds a root item that will not be visible
	wxTreeItemId rootID = tctl->AddRoot( wxT("Root") );

	// appends subfolders
	CVirtualPaths pth;
	CNullableLong nl;
	nl.SetNull(true);
	pth.DBStartQueryListPaths( nl );
	while( !pth.IsEOF() ) {
		wxString name = pth.PathName;
		// adds the folder to the tree
		wxTreeItemId itemID = tctl->AppendItem( rootID, name, 1, 2, 
							new MyTreeItemData(name, pth.PathID, pth.PhysPathID) );
		if( pth.PhysPathID.IsNull() ) {
			// this vistual path has been created by the user: it is not a physical path assigned to a virtual path
			// show it in a different colour
			tctl->SetItemTextColour( itemID, *wxBLUE );
		}
		// sets the expanded images
		tctl->SetItemImage( itemID, 1, wxTreeItemIcon_Expanded );
		tctl->SetItemImage( itemID, 2, wxTreeItemIcon_SelectedExpanded );
		// adds the subfolders
		LoadVirtualFolderInTreeControl( tctl, itemID, pth.PathID );

		pth.DBNextRow();
	}
}

void CMainFrame::LoadVirtualFolderInTreeControl( wxTreeCtrl* tctl, wxTreeItemId fatherTreeID, long fatherID ) {

	CVirtualPaths pth;
	pth.DBStartQueryListPaths( fatherID );
	while( !pth.IsEOF() ) {
		wxString name = pth.PathName;
		name = name.AfterLast( wxFileName::GetPathSeparator() );
		// adds the folder to the tree
		wxTreeItemId itemID = tctl->AppendItem( fatherTreeID, name, 1, 2, 
							new MyTreeItemData(name, pth.PathID, pth.PhysPathID) );
		if( pth.PhysPathID.IsNull() ) {
			// this vistual path has been created by the user: it is not a physical path assigned to a virtual path
			// show it in a different colour
			tctl->SetItemTextColour( itemID, *wxBLUE );
		}
		// sets the expanded images
		tctl->SetItemImage( itemID, 1, wxTreeItemIcon_Expanded );
		tctl->SetItemImage( itemID, 2, wxTreeItemIcon_SelectedExpanded );

		pth.DBNextRow();
	}
}



/*!
 * wxEVT_COMMAND_TREE_ITEM_EXPANDING event handler for ID_TREE_CONTROL
 */

void CMainFrame::OnTreeControlItemExpanding( wxTreeEvent& event )
{
	wxTreeCtrl* tctl = GetTreePhysicalControl();
	wxTreeItemId itemID = event.GetItem();
    MyTreeItemData *itemData = (MyTreeItemData *) tctl->GetItemData(itemID);

	if( itemData->IsVolume() || itemData->AlreadyOpened() ) return;
		
	// if this item has not been yet opened it loads the children of its children
	itemData->SetAlreadyOpened();

	// loops over the children
	wxTreeItemIdValue cookie;
	wxTreeItemId childID = tctl->GetFirstChild( itemID, cookie );
	while( childID.IsOk() ) {
		// adds the children of this child
	    MyTreeItemData *childItemData = (MyTreeItemData *) tctl->GetItemData(childID);
		LoadFolderInTreeControl( childItemData->GetVolumeID(), tctl, childID, childItemData->GetPathID() );
		childID = tctl->GetNextChild( itemID, cookie );
	}
}


/*!
 * wxEVT_COMMAND_TREE_SEL_CHANGED event handler for ID_TREE_CONTROL
 */

void CMainFrame::OnTreeControlSelChanged( wxTreeEvent& event )
{
	if( m_CurrentView != Physical ) return;

	wxTreeItemId itemID = event.GetItem();
	ShowFolderFiles( itemID );
}


/*!
 * wxEVT_COMMAND_TREE_SEL_CHANGED event handler for ID_TREE_CONTROL_VIRTUAL
 */

void CMainFrame::OnTreeControlVirtualSelChanged( wxTreeEvent& event )
{
	if( m_CurrentView != Virtual ) return;
	
	wxTreeItemId itemID = event.GetItem();
	ShowVirtualFolderFiles( itemID );
}


void CMainFrame::CreateListControlHeaders(void) {

	wxListCtrl* lctl = GetListControl();
	DeleteAllListControlItems();

	lctl->Hide();

	lctl->ClearAll();

	// adds the columns to the list control
	wxListItem itemCol;
	itemCol.SetText( _("Name") );
	itemCol.SetAlign( wxLIST_FORMAT_LEFT );
	itemCol.SetImage( -1 );
	lctl->InsertColumn( 0, itemCol );

	itemCol.SetText( _("Size") );
	itemCol.SetAlign( wxLIST_FORMAT_RIGHT );
	lctl->InsertColumn( 1, itemCol );

	itemCol.SetText( _("Ext") );
	itemCol.SetAlign( wxLIST_FORMAT_LEFT );
	lctl->InsertColumn( 2, itemCol );

	itemCol.SetText( _("Last modified") );
	itemCol.SetAlign( wxLIST_FORMAT_LEFT );
	lctl->InsertColumn( 3, itemCol );

	if( m_CurrentView == Virtual || m_CurrentView == Search ) {
		itemCol.SetText( _("Physical path") );
		itemCol.SetAlign( wxLIST_FORMAT_LEFT );
		lctl->InsertColumn( 4, itemCol );
	}

	// assigns the image list
	wxImageList* iml = new wxImageList( 16, 16 );
	iml->Add(wxIcon(folder_closed_xpm));
	iml->Add(wxIcon(deffile_xpm));
	lctl->AssignImageList( iml, wxIMAGE_LIST_SMALL );

	// adds a dummy row and deletes it
	// needed to correctly show the headers
	wxListItem item;
	item.SetMask( wxLIST_MASK_STATE|wxLIST_MASK_TEXT|wxLIST_MASK_IMAGE|wxLIST_MASK_DATA );
	int i = lctl->InsertItem( item );
	lctl->SetItem( i, 0, "a" );
	lctl->SetItem( i, 1, "a" );
	lctl->SetItem( i, 2, "a" );
	lctl->SetItem( i, 3, "a" );
	if( m_CurrentView == Virtual )
		lctl->SetItem( i, 4, "a" );

	if( m_CurrentView == Physical ) {
		lctl->SetColumnWidth( 0, m_ListviewColWidthPhysical[0] );
		lctl->SetColumnWidth( 1, m_ListviewColWidthPhysical[1] );
		lctl->SetColumnWidth( 2, m_ListviewColWidthPhysical[2] );
		lctl->SetColumnWidth( 3, m_ListviewColWidthPhysical[3] );
	}
	else {
		lctl->SetColumnWidth( 0, m_ListviewColWidthVirtual[0] );
		lctl->SetColumnWidth( 1, m_ListviewColWidthVirtual[1] );
		lctl->SetColumnWidth( 2, m_ListviewColWidthVirtual[2] );
		lctl->SetColumnWidth( 3, m_ListviewColWidthVirtual[3] );
		lctl->SetColumnWidth( 4, m_ListviewColWidthVirtual[4] );
	}

	lctl->DeleteAllItems();
	lctl->Show();
}

/*!
 * wxEVT_COMMAND_MENU_SELECTED event handler for wxID_OPEN
 */

void CMainFrame::OnOPENClick( wxCommandEvent& WXUNUSED(event) )
{
	wxString caption = _("Open catalog");
	wxString wildcard = _("VVV  files (*.vvv)|*.vvv|All files (*.*)|*.*");
	wxFileDialog fd( this, caption, wxEmptyString, wxEmptyString, wildcard, wxOPEN );
	if( fd.ShowModal() == wxID_OK ) {
		wxString path = fd.GetPath();
		if ( path.empty() ) return;
		OpenDatabase( path, CUtils::GetExpectedDatabaseVersion() );
	}
}

CMainFrame::~CMainFrame() {

	if( m_CurrentView == Physical ) 
		StoreListControlPhysicalWidth();
	else
		StoreListControlVirtualWidth();

	DeleteAllListControlItems();	// to delete item data

	wxConfigBase *pConfig = wxConfigBase::Get();
	if ( pConfig == NULL )
		return;

	// saves the frame position
	int x, y, w, h;
	GetClientSize(&w, &h);
	GetPosition(&x, &y);
	pConfig->SetPath(wxT("/Mainframe/Layout"));
	if( !IsMaximized() ) {
		pConfig->Write(wxT("x"), (long) x);
		pConfig->Write(wxT("y"), (long) y);
		pConfig->Write(wxT("w"), (long) w);
		pConfig->Write(wxT("h"), (long) h);
	}
	pConfig->Write(wxT("Maximized"), IsMaximized() );

	// saves the sash position
	wxSplitterWindow* sw = GetSplitterWindow();
	pConfig->Write(wxT("SashPosition"), (long) sw->GetSashPosition() );

	// saves the MRU files list
	m_fileHistory->Save( *pConfig );
	delete m_fileHistory;

	// saves the listview columns width
	pConfig->SetPath(wxT("/Mainframe/Layout/ListViewPhysical"));
	pConfig->Write(wxT("cw0"), (long) m_ListviewColWidthPhysical[0]);
	pConfig->Write(wxT("cw1"), (long) m_ListviewColWidthPhysical[1]);
	pConfig->Write(wxT("cw2"), (long) m_ListviewColWidthPhysical[2]);
	pConfig->Write(wxT("cw3"), (long) m_ListviewColWidthPhysical[3]);
	pConfig->SetPath(wxT("/Mainframe/Layout/ListViewVirtual"));
	pConfig->Write(wxT("cw0"), (long) m_ListviewColWidthVirtual[0]);
	pConfig->Write(wxT("cw1"), (long) m_ListviewColWidthVirtual[1]);
	pConfig->Write(wxT("cw2"), (long) m_ListviewColWidthVirtual[2]);
	pConfig->Write(wxT("cw3"), (long) m_ListviewColWidthVirtual[3]);
	pConfig->Write(wxT("cw4"), (long) m_ListviewColWidthVirtual[4]);

	// delete the virtual folders window
	if( m_ChooseVirtualFolderDialog != NULL ) delete m_ChooseVirtualFolderDialog;

}
/*!
 * wxEVT_COMMAND_MENU_SELECTED event handler for ID_VIEW_PHYSICAL
 */

void CMainFrame::OnViewPhysicalClick( wxCommandEvent& event )
{
	if( !event.IsChecked() ) return;
	if( m_CurrentView == Physical ) return;

	wxSplitterWindow* sw = GetSplitterWindow();
	long sp = sw->GetSashPosition();
	wxListCtrl* lctl = GetListControl();
	sw->Unsplit();
	switch( m_CurrentView ) {
		case Virtual:
			HideVirtualView();
			break;
		case Search:
			HideSearchView();
			break;
		default:
			wxASSERT(true);
	}
	ShowPhysicalView();
	sw->SplitVertically( GetTreePhysicalControl(), lctl );
	sw->SetSashPosition( sp );
	UpdateStatusBar( nPhysicalFiles, sizePhysicalFiles );

}

/*!
 * wxEVT_COMMAND_MENU_SELECTED event handler for ID_VIEW_VIRTUAL
 */

void CMainFrame::OnViewVirtualClick( wxCommandEvent& event )
{
	if( !event.IsChecked() ) return;
	if( m_CurrentView == Virtual ) return;

	wxSplitterWindow* sw = GetSplitterWindow();
	long sp = sw->GetSashPosition();
	wxListCtrl* lctl = GetListControl();
	sw->Unsplit();
	switch( m_CurrentView ) {
		case Physical:
			HidePhysicalView();
			break;
		case Search:
			HideSearchView();
			break;
		default:
			wxASSERT(true);
	}
	ShowVirtualView();
	sw->SplitVertically( GetTreeVirtualControl(), lctl );
	sw->SetSashPosition( sp );
	UpdateStatusBar( nVirtualFiles, sizeVirtualFiles );

}


/*!
 * wxEVT_COMMAND_TREE_ITEM_EXPANDING event handler for ID_TREE_CONTROL_VIRTUAL
 */

void CMainFrame::OnTreeControlVirtualItemExpanding( wxTreeEvent& event )
{
	wxTreeCtrl* tctl = GetTreeVirtualControl();
	wxTreeItemId itemID = event.GetItem();
    MyTreeItemData *itemData = (MyTreeItemData *) tctl->GetItemData(itemID);

	if( itemData->AlreadyOpened() ) return;
		
	// if this item has not been yet opened it loads the children of its children
	itemData->SetAlreadyOpened();

	// loops over the children
	wxTreeItemIdValue cookie;
	wxTreeItemId childID = tctl->GetFirstChild( itemID, cookie );
	while( childID.IsOk() ) {
		// adds the children of this child
	    MyTreeItemData *childItemData = (MyTreeItemData *) tctl->GetItemData(childID);
		LoadVirtualFolderInTreeControl( tctl, childID, childItemData->GetPathID() );
		childID = tctl->GetNextChild( itemID, cookie );
	}
}


void CMainFrame::DeleteAllListControlItems(void) {
	wxListCtrl* lctl = GetListControl();
	int nItems = lctl->GetItemCount();
	for( int i = 0; i < nItems; i++ ) {
		long itemData = lctl->GetItemData( i );
		delete (MyListItemData*) itemData;
	}
	lctl->DeleteAllItems();
}



// shows in the listview the files contained in the passed folder
void CMainFrame::ShowFolderFiles( wxTreeItemId itemID ) {

	wxBusyCursor wait;

	wxTreeCtrl* tctl = GetTreePhysicalControl();
	wxListCtrl* lctl = GetListControl();
	
	// assigns the image list
	wxImageList* iml = new wxImageList( 16, 16 );
	iml->Add(wxIcon(folder_closed_xpm));
	iml->Add(wxIcon(deffile_xpm));
	lctl->AssignImageList( iml, wxIMAGE_LIST_SMALL );

    MyTreeItemData *itemData = (MyTreeItemData *) tctl->GetItemData(itemID);
	if( itemData == NULL ) return;

	lctl->Hide();	// to speed up things

	DeleteAllListControlItems();

	// retrieves the files contained in the selected folder
	nPhysicalFiles = 0;
	sizePhysicalFiles = 0;
	CFiles files;
	files.DBStartQueryListFiles( itemData->GetPathID() );
	while( !files.IsEOF() ) {
		// adds the file to the list control
		int imageIndex = (files.IsFolder() ? 0 : 1 );

		wxListItem item;
		item.SetMask( wxLIST_MASK_STATE|wxLIST_MASK_TEXT|wxLIST_MASK_IMAGE|wxLIST_MASK_DATA );
		int i = lctl->InsertItem( item );
		lctl->SetItem( i, 0, files.FileName, imageIndex );
		lctl->SetItem( i, 1, files.IsFolder() ? "" : CUtils::HumanReadableFileSize(files.FileSize) );
		lctl->SetItem( i, 2, files.FileExt );
		lctl->SetItem( i, 3, files.DateTime.FormatDate() + " " + files.DateTime.FormatTime() );
		lctl->SetItemData( i, (long) new MyListItemData( files.PathFileID.IsNull() ? 0 : (long) files.PathFileID, files.FileName, files.FileExt, files.FileSize, files.DateTime, files.IsFolder() ) );
		nPhysicalFiles++;
		sizePhysicalFiles += files.FileSize;

		files.DBNextRow();
	}

	lctl->SortItems( ListControlCompareFunction, 0 );
	lctl->Show();

	UpdateStatusBar( nPhysicalFiles, sizePhysicalFiles );
}

// shows in the listview the files contained in the currently selected folder
void CMainFrame::ShowSelectedFolderFiles(void ) {

	wxTreeCtrl* tctl = GetTreePhysicalControl();
    wxTreeItemId itemID = tctl->GetSelection();
	if( itemID.IsOk() ) {
		ShowFolderFiles( itemID );
	}
	else {
		DeleteAllListControlItems();
	}
}

// shows in the listview the files contained in the passed virtual folder
void CMainFrame::ShowVirtualFolderFiles( wxTreeItemId itemID ) {

	wxBusyCursor wait;

	wxTreeCtrl* tctl = GetTreeVirtualControl();
	wxListCtrl* lctl = GetListControl();
	
	// assigns the image list
	wxImageList* iml = new wxImageList( 16, 16 );
	iml->Add(wxIcon(folder_closed_xpm));
	iml->Add(wxIcon(deffile_xpm));
	lctl->AssignImageList( iml, wxIMAGE_LIST_SMALL );

	// retrieves info about the selected item
    MyTreeItemData *itemData = (MyTreeItemData *) tctl->GetItemData(itemID);
	if( itemData == NULL ) return;
	
	lctl->Hide();	// to speed up things

	DeleteAllListControlItems();

	// retrieves the files contained in the selected folder
	nVirtualFiles = 0;
	sizeVirtualFiles = 0;
	CVirtualFiles files;
	files.DBStartQueryListFiles( itemData->GetPathID() );
	while( !files.IsEOF() ) {
		wxString prevFileName = files.FileName;
		bool wasFolder = files.IsFolder();

		int i = AddRowToVirtualListControl( lctl, files.IsFolder(), files.FileName, files.FileSize, files.FileExt, files.DateTime, files.FullPhysicalPath, files.VirtualPathFileID.IsNull() ? 0 : (long) files.VirtualPathFileID );

		nVirtualFiles++;
		sizeVirtualFiles += files.FileSize;

		files.DBNextRow();

		// removes possible duplicate folder rows. If this folder contains physical folders from different volumes
		// but with the same name the query will return more than one folder with the same name
		if( wasFolder ) {
			while( !files.IsEOF() ) {

				if( files.FileName != prevFileName ) break;
				if( !files.IsFolder() ) break;

				// here if the current row is a folder with the same name as the one already in the listview
				lctl->SetItem( i, 4, "" );	// remove physical path since it has no meaning (there are more than one)

				files.DBNextRow();	// sjip this row
			}
		}

	}

	lctl->SortItems( ListControlCompareFunction, 0 );
	lctl->Show();

	UpdateStatusBar( nVirtualFiles, sizeVirtualFiles );
}

// shows in the listview the files contained in the currently selected virtual folder
void CMainFrame::ShowSelectedVirtualFolderFiles(void ) {

	wxTreeCtrl* tctl = GetTreeVirtualControl();
    wxTreeItemId itemID = tctl->GetSelection();
	if( itemID.IsOk() ) {
		ShowVirtualFolderFiles( itemID );
	}
	else {
		DeleteAllListControlItems();
	}
}


/*!
 * wxEVT_UPDATE_UI event handler for ID_RENAME_VOLUME
 */

void CMainFrame::OnRenameVolumeUpdate( wxUpdateUIEvent& event )
{
	if( CBaseDB::GetDatabase() == NULL || m_CurrentView != Physical ) {
		event.Enable(false);
		return;
	}
	
	bool hideElement = false;
	wxTreeCtrl *tctl = GetTreePhysicalControl();
	if( tctl->GetCount() > 0 ) {
		wxTreeItemId item = tctl->GetSelection();
		if( item.IsOk() ) {
			if( tctl->GetItemParent(item) != tctl->GetRootItem() ) hideElement = true;
		}
		else {
			hideElement = true;
		}
	}
	else
		hideElement = true;

	event.Enable( !hideElement );
}

/*!
 * wxEVT_UPDATE_UI event handler for ID_DELETE_VOLUME
 */

void CMainFrame::OnDeleteVolumeUpdate( wxUpdateUIEvent& event )
{
	if( CBaseDB::GetDatabase() == NULL || m_CurrentView != Physical ) {
		event.Enable(false);
		return;
	}
	
	bool hideElement = false;
	wxTreeCtrl *tctl = GetTreePhysicalControl();
	if( tctl->GetCount() > 0 ) {
		wxTreeItemId item = tctl->GetSelection();
		if( item.IsOk() ) {
			if( tctl->GetItemParent(item) != tctl->GetRootItem() ) hideElement = true;
		}
		else {
			hideElement = true;
		}
	}
	else
		hideElement = true;

	event.Enable( !hideElement );
}


/*!
 * wxEVT_COMMAND_MENU_SELECTED event handler for ID_RENAME_VOLUME
 */

void CMainFrame::OnRenameVolumeClick( wxCommandEvent& WXUNUSED(event) )
{
	wxTreeCtrl *tctl = GetTreePhysicalControl();
	wxTreeItemId item = tctl->GetSelection();
	wxString oldName = tctl->GetItemText(item);

	// asks for the new volume name
	wxTextEntryDialog ted( this, _("Enter the new volume name"), _("Rename volume"), oldName, wxOK | wxCANCEL );
	if( ted.ShowModal() != wxID_OK ) return;
	wxString newName = ted.GetValue();
	if( newName == oldName || newName.empty() ) return;

	// changes the volume name in the database
    MyTreeItemData *itemData = (MyTreeItemData *) tctl->GetItemData(item);
	CVolumes vol( itemData->GetVolumeID() );	// loads the current data
	vol.VolumeName = newName;
	try {
		vol.DbUpdate();
	}
	catch( CDataErrorException& e ) {
		if( e.GetErrorCause() == CDataErrorException::Unique ) {
			CUtils::MsgErr( _("The new volume name is already present in the database") );
			return;
		}
		else
			throw;
	}

	// changes the volume name in the tree control
	tctl->SetItemText( item, newName );

}


/*!
 * wxEVT_COMMAND_MENU_SELECTED event handler for ID_ADD_VIRTUAL_FOLDER
 */

void CMainFrame::OnAddVirtualFolderClick( wxCommandEvent& WXUNUSED(event) )
{
	m_ChooseVirtualFolderDialog->ShowModal();
	long virtualFolderId = m_ChooseVirtualFolderDialog->GetVirtualFolderID();
	if( virtualFolderId < 0 ) return;

	bool isVolumeItem = false;	// true if the user has selected a volume (not a folder)
	wxTreeCtrl *tctl = GetTreePhysicalControl();
	wxTreeItemId item = tctl->GetSelection();
	if( tctl->GetItemParent(item) == tctl->GetRootItem() ) isVolumeItem = true;

	wxBusyCursor wait;

	MyTreeItemData *itemData = (MyTreeItemData *) tctl->GetItemData(item);
	long physicalFolderId = itemData->GetPathID();

	if( isVolumeItem ) {
		long volumeID = itemData->GetVolumeID();
		CVirtualPaths::AppendVolume( volumeID, physicalFolderId, virtualFolderId );
	}
	else
		CVirtualPaths::AppendPhysicalPath( physicalFolderId, virtualFolderId );

	// updates the tree controls
	m_ChooseVirtualFolderDialog->Refresh();
	LoadVirtualTreeControl();
}


/*!
 * wxEVT_UPDATE_UI event handler for ID_ADD_VIRTUAL_FOLDER
 */

void CMainFrame::OnAddVirtualFolderUpdate( wxUpdateUIEvent& event )
{
	if( CBaseDB::GetDatabase() == NULL ) {
		event.Enable(false);
		return;
	}
	
	bool isEnabled = m_CurrentView == Physical;
	if( isEnabled ) {
		wxTreeCtrl* tctl = GetTreePhysicalControl();
		isEnabled = (tctl->GetCount() > 0);
	}

	event.Enable( isEnabled );
}


/*!
 * wxEVT_COMMAND_MENU_SELECTED event handler for ID_NEW_VIRTUAL_ROOT_FOLDER
 */

void CMainFrame::OnNewVirtualRootFolderClick( wxCommandEvent& WXUNUSED(event) )
{
	CNullableLong nl;
	nl.SetNull( true );

	CreateNewVirtualFolder( nl, _("New virtual root folder") );

	m_ChooseVirtualFolderDialog->Refresh();
}

/*!
 * wxEVT_UPDATE_UI event handler for ID_NEW_VIRTUAL_ROOT_FOLDER
 */

void CMainFrame::OnNewVirtualRootFolderUpdate( wxUpdateUIEvent& event )
{
	if( CBaseDB::GetDatabase() == NULL ) {
		event.Enable(false);
		return;
	}
	
	event.Enable( m_CurrentView == Virtual );
}

/*!
 * wxEVT_COMMAND_MENU_SELECTED event handler for ID_NEW_VIRTUAL_SUBFOLDER
 */

void CMainFrame::OnNewVirtualSubfolderClick( wxCommandEvent& WXUNUSED(event) )
{
	wxTreeCtrl *tctl = GetTreeVirtualControl();
	wxTreeItemId item = tctl->GetSelection();
    MyTreeItemData *itemData = (MyTreeItemData *) tctl->GetItemData(item);
	long FatherID = itemData->GetPathID();

	CreateNewVirtualFolder( FatherID, _("New virtual subfolder") );

	m_ChooseVirtualFolderDialog->Refresh();
}

void CMainFrame::CreateNewVirtualFolder( CNullableLong FatherID, wxString windowTitle ) {
	wxTreeCtrl *tctl = GetTreeVirtualControl();
	wxTreeItemId fatherItem;
	wxString folderName = "";

	if( FatherID.IsNull() ) {
		// this is a root folder
		fatherItem = tctl->GetRootItem();
	}
	else {
		// this is a subfolder
		fatherItem = tctl->GetSelection();
	}

	// asks for the new folder name
	wxTextEntryDialog ted( this, _("Enter the new folder name"), windowTitle, folderName, wxOK | wxCANCEL );
	if( ted.ShowModal() != wxID_OK ) return;
	folderName = ted.GetValue();
	if( folderName == "" ) return;

	// adds the new folder to the database
	CVirtualPaths pth;
	pth.PathName = folderName;
	pth.PhysPathID.SetNull( true );
	pth.FatherID = FatherID;
	try {
		pth.DbInsert();
	}
	catch( CDataErrorException& e ) {
		if( e.GetErrorCause() == CDataErrorException::Unique ) {
			CUtils::MsgErr( _("The new folder name is already present in the database") );
			return;
		}
		else
			throw;
	}

	// adds the folder to the tree control
	wxTreeItemId newItem = tctl->AppendItem( fatherItem, pth.PathName, 1, 2, 
						new MyTreeItemData(pth.PathName, pth.PathID, pth.PhysPathID) );
	tctl->SetItemTextColour( newItem, *wxBLUE );
	// sets the expanded images
	tctl->SetItemImage( newItem, 1, wxTreeItemIcon_Expanded );
	tctl->SetItemImage( newItem, 2, wxTreeItemIcon_SelectedExpanded );

	// updates the listview
	if( !FatherID.IsNull() ) 
		ShowVirtualFolderFiles( fatherItem );

	m_ChooseVirtualFolderDialog->Refresh();
}

/*!
 * wxEVT_UPDATE_UI event handler for ID_NEW_VIRTUAL_SUBFOLDER
 */

void CMainFrame::OnNewVirtualSubfolderUpdate( wxUpdateUIEvent& event )
{
	if( CBaseDB::GetDatabase() == NULL ) {
		event.Enable(false);
		return;
	}
	
	bool isEnabled = m_CurrentView == Virtual;
	if( isEnabled ) {
		wxTreeCtrl* tctl = GetTreeVirtualControl();
		isEnabled = (tctl->GetCount() > 0);
		if( isEnabled ) {
			wxTreeItemId item = tctl->GetSelection();
			isEnabled = item.IsOk();
		}
	}
	event.Enable( isEnabled );
}

/*!
 * wxEVT_COMMAND_MENU_SELECTED event handler for ID_RENAME_VIRTUAL_FOLDER
 */

void CMainFrame::OnRenameVirtualFolderClick( wxCommandEvent& WXUNUSED(event) )
{
	wxTreeCtrl *tctl = GetTreeVirtualControl();
	wxTreeItemId item = tctl->GetSelection();
	wxString oldName = tctl->GetItemText(item);

	// asks for the new volume name
	wxTextEntryDialog ted( this, _("Enter the new forder name"), _("Rename virtual folder"), oldName, wxOK | wxCANCEL );
	if( ted.ShowModal() != wxID_OK ) return;
	wxString newName = ted.GetValue();
	if( newName == oldName || newName.empty() ) return;

	// changes the folder name in the database
    MyTreeItemData *itemData = (MyTreeItemData *) tctl->GetItemData(item);
	try {
		CVirtualPaths::Rename( itemData->GetPathID(), newName );
	}
	catch( CDataErrorException& e ) {
		if( e.GetErrorCause() == CDataErrorException::Unique ) {
			CUtils::MsgErr( _("The new folder name is already present in the database") );
			return;
		}
		else
			throw;
	}

	// changes the volume name in the tree control
	tctl->SetItemText( item, newName );

	m_ChooseVirtualFolderDialog->Refresh();
}

/*!
 * wxEVT_UPDATE_UI event handler for ID_RENAME_VIRTUAL_FOLDER
 */

void CMainFrame::OnRenameVirtualFolderUpdate( wxUpdateUIEvent& event )
{
	if( CBaseDB::GetDatabase() == NULL ) {
		event.Enable(false);
		return;
	}
	
	bool isEnabled = m_CurrentView == Virtual;
	if( isEnabled ) {
		wxTreeCtrl* tctl = GetTreeVirtualControl();
		isEnabled = (tctl->GetCount() > 0);
		if( isEnabled ) {
			wxTreeItemId item = tctl->GetSelection();
			if( item.IsOk() ) {
				MyTreeItemData *itemData = (MyTreeItemData *) tctl->GetItemData(item);
				isEnabled = itemData->GetPhysPathID().IsNull();
			}
			else
				isEnabled = false;
		}
	}
	event.Enable( isEnabled );
}

/*!
 * wxEVT_COMMAND_MENU_SELECTED event handler for ID_DELETE_VIRTUAL_FOLDER
 */

void CMainFrame::OnDeleteVirtualFolderClick( wxCommandEvent& WXUNUSED(event) )
{
	if( !CUtils::MsgAskNo( _("This command will delete the selected virtual foder, but it will not change the folders in the physical view.\n\nDo you really want to delete the selected virtual folder?") ) )
		return;
	
	wxTreeCtrl *tctl = GetTreeVirtualControl();
	wxTreeItemId item = tctl->GetSelection();
    MyTreeItemData *itemData = (MyTreeItemData *) tctl->GetItemData(item);

	// deletes from the database
	CVirtualPaths vp;
	vp.PathID = itemData->GetPathID();
	vp.DbDelete();

	// deletes from the tree control
	tctl->DeleteChildren(item);
	tctl->Delete(item);

	m_ChooseVirtualFolderDialog->Refresh();
}

/*!
 * wxEVT_UPDATE_UI event handler for ID_DELETE_VIRTUAL_FOLDER
 */

void CMainFrame::OnDeleteVirtualFolderUpdate( wxUpdateUIEvent& event )
{
	if( CBaseDB::GetDatabase() == NULL ) {
		event.Enable(false);
		return;
	}
	
	bool isEnabled = m_CurrentView == Virtual;
	if( isEnabled ) {
		wxTreeCtrl* tctl = GetTreeVirtualControl();
		isEnabled = (tctl->GetCount() > 0);
		if( isEnabled ) {
			wxTreeItemId item = tctl->GetSelection();
			isEnabled = item.IsOk();
		}
	}
	event.Enable( isEnabled );
}


void CMainFrame::OnMRUFile( wxCommandEvent& event ) {
	
	int i = event.GetId() - wxID_FILE1;
	wxString fileName = m_fileHistory->GetHistoryFile( i );
	if( fileName.empty() ) return;
	if( !wxFileName::FileExists(fileName) ) {
		CUtils::MsgErr( "This catalog file does not exist any more" );
		m_fileHistory->RemoveFileFromHistory( i );
		return;
	}
	OpenDatabase( fileName, CUtils::GetExpectedDatabaseVersion() );

}


void CMainFrame::OpenDatabase( wxString fileName, int expectedVersion ) {

	wxBusyCursor wait;

	CBaseDB *db = CBaseDB::GetDatabase();
	if( db != NULL ) {
		CBaseDB::GetDatabase()->Disconnect();
		CBaseDB::DeleteFirebirdDatabase();
	}
	
	CBaseDB::CreateFirebirdDatabase( "", fileName, "SYSDBA", "masterkey" );
	wxString stmp = CBaseDB::GetDatabase()->Connect();

	int dbVersion = CBaseDB::GetDatabase()->GetDatabaseVersion();

	if( dbVersion < expectedVersion ) {
		// we need to upgrade the database

		if( !wxFileExists(CUtils::GetStructUpdateDbName() ) ) {
			CUtils::MsgErr( _("This catalog has been created with a previous version of the program and it needs to be upgraded, but the file containing the upgrades list is missing.\n\nYou can try reinstalling the program to solve this problem.") );
			return;
		}

		wxBusyInfo bi( _("Upgrading the catalog, please wait...") );
		CBaseDB::GetDatabase()->UpgradeDatabase( dbVersion );
	}

	LoadTreeControl();
	LoadVirtualTreeControl();

	DeleteAllListControlItems();

	// creates the dialog used to choose a virtual folder
	// we use a global object to keep folders selection between dialog calls
	if( m_ChooseVirtualFolderDialog != NULL ) delete m_ChooseVirtualFolderDialog;
	m_ChooseVirtualFolderDialog = new CDialogChooseVirtualFolder(this, ID_DIALOG_CHOOSE_VIRTUAL_FOLDER, _("Choose virtual folder"));

	// stores the file in the MRU list
	m_fileHistory->AddFileToHistory( fileName );

	// sets the main window caption
	SetTitle( fileName + " - " + CUtils::GetApplicationName() );

}
/*!
 * wxEVT_COMMAND_LIST_COL_CLICK event handler for ID_LIST_CONTROL
 */

void CMainFrame::OnListControlColLeftClick( wxListEvent& event )
{
	int nCol = event.GetColumn();
	if( nCol == m_ListViewSortColumn ) {
		m_ListViewSortAscending = !m_ListViewSortAscending;
	}
	else {
		m_ListViewSortColumn = nCol;
		m_ListViewSortAscending = true;
	}

	wxListCtrl* lctl = GetListControl();
	lctl->SortItems( ListControlCompareFunction, 0 );

}


/*!
 * wxEVT_UPDATE_UI event handler for ID_VIEW_PHYSICAL
 */

void CMainFrame::OnViewPhysicalUpdate( wxUpdateUIEvent& event )
{
	event.Enable( CBaseDB::GetDatabase() != NULL );
	
	if( m_CurrentView == Physical )
		event.Check(true);
	else
		event.Check(false);
}

/*!
 * wxEVT_UPDATE_UI event handler for ID_VIEW_VIRTUAL
 */

void CMainFrame::OnViewVirtualUpdate( wxUpdateUIEvent& event )
{
	event.Enable( CBaseDB::GetDatabase() != NULL );
	
	if( m_CurrentView == Virtual )
		event.Check(true);
	else
		event.Check(false);
}

/*!
 * wxEVT_UPDATE_UI event handler for ID_CATALOG_VOLUME
 */

void CMainFrame::OnCatalogVolumeUpdate( wxUpdateUIEvent& event )
{
	event.Enable( CBaseDB::GetDatabase() != NULL );
}

/*!
 * wxEVT_COMMAND_MENU_SELECTED event handler for ID_VIEW_TOOLBAR
 */

void CMainFrame::OnViewToolbarClick( wxCommandEvent& event )
{
	if( event.IsChecked() )
		GetToolBar()->Show(true);
	else {
		GetToolBar()->Show(false);
	}
#ifdef __WXMSW__
	SendSizeEvent();
#else
	wxSize s = GetSize();
	Fit();
	SetSize(s);
#endif
}

void CMainFrame::StoreListControlVirtualWidth(void) {

	wxListCtrl* lctl = GetListControl();
	wxASSERT(lctl->GetColumnCount() == 5);

	for( int k = 0; k < 5; k++ )
		m_ListviewColWidthVirtual[k] = lctl->GetColumnWidth(k);
}

void CMainFrame::StoreListControlPhysicalWidth(void) {

	wxListCtrl* lctl = GetListControl();
	wxASSERT(lctl->GetColumnCount() == 4);

	for( int k = 0; k < 4; k++ )
		m_ListviewColWidthPhysical[k] = lctl->GetColumnWidth(k);
}

/*!
 * wxEVT_COMMAND_MENU_SELECTED event handler for ID_DELETE_VOLUME
 */

void CMainFrame::OnDeleteVolumeClick( wxCommandEvent& WXUNUSED(event) )
{
	wxTreeCtrl *tctl = GetTreePhysicalControl();
	wxTreeItemId item = tctl->GetSelection();
    MyTreeItemData *itemData = (MyTreeItemData *) tctl->GetItemData(item);

	if( !CUtils::MsgAskNo( _("This command will delete this volume:\n\n") + tctl->GetItemText(item) + _("\n\nDo you really want to delete this volume?") ) )
		return;

	CVolumes vol;
	vol.VolumeID = itemData->GetVolumeID();
	try {
		vol.DbDelete();
	}
	catch( CDataErrorException& e ) {
		if( e.GetErrorCause() == CDataErrorException::ReferentialIntegrity ) {
			CUtils::MsgErr( _("Unable to delete this volume: at least one of its files is used in the virtual view") );
			return;
		}
		else
			throw;
	}

	// removes the item from the tree control
	tctl->Delete(item);
}

/*!
 * wxEVT_COMMAND_MENU_SELECTED event handler for wxID_EXIT
 */

void CMainFrame::OnEXITClick( wxCommandEvent& WXUNUSED(event) )
{
	Close(true);
}

/*!
 * wxEVT_COMMAND_MENU_SELECTED event handler for wxID_ABOUT
 */

void CMainFrame::OnABOUTClick( wxCommandEvent& WXUNUSED(event) )
{
	wxAboutDialogInfo info;
	info.SetName( "VVV" );
	info.SetVersion( CUtils::GetApplicationVersion() );
	info.SetWebSite( "http://vvvapp.sourceforge.net/" );
	info.SetDescription( _("VVV (Virtual Volumes View): a program to catalog removable devices like CDs and DVDs\n\n\"The mud of Venaus is the blood of this land\"") );
	info.SetCopyright( _("Copyright (C) 2007 The VVV Team") );
	info.AddDeveloper( "Fulvio Senore" );
	info.AddArtist( _("This program uses the Tango icons (http://tango.freedesktop.org/Tango_Desktop_Project )") );
	info.SetLicence( _("This is open source software, distributed under the GNU GENERAL PUBLIC LICENSE") );

	wxAboutBox( info );
}

/*!
 * wxEVT_COMMAND_MENU_SELECTED event handler for wxID_NEW
 */

void CMainFrame::OnNEWClick( wxCommandEvent& WXUNUSED(event) )
{
	wxString caption = _("New catalog");
	wxString wildcard = _("VVV  files (*.vvv)|*.vvv|All files (*.*)|*.*");
	wxFileDialog fd( this, caption, wxEmptyString, wxEmptyString, wildcard, wxSAVE );
	if( fd.ShowModal() != wxID_OK ) return;

	wxString databaseFile = fd.GetPath();
	if ( databaseFile.empty() ) return;

	// add an extension if needed
	{
		wxFileName fn(databaseFile);
		if( fn.GetExt().empty() )
			databaseFile += ".vvv";
	}

	// check if the database already exists
	if( wxFileExists(databaseFile) ) {
		CUtils::MsgErr( _("Unable to create the new catalog. You have choosen an existing file:\n\n" + databaseFile + "\n\nYou must type the name of a non-existing file.") );
		return;
	}

	// check if we can create the database
	wxFile f;
	{
		wxLogNull ln;
		if( !f.Create(databaseFile) ) {
			CUtils::MsgErr( _("Unable to create the new catalog: you have choosen a folder where you do not have the right to create a file.") );
			return;
		}
	}
	f.Close();
	wxRemoveFile(databaseFile);

	// creates the name of the database backup file to restore
	wxString appPath = wxStandardPaths::Get().GetExecutablePath();
	wxFileName fn(appPath);
	wxString path = fn.GetPath( wxPATH_GET_VOLUME | wxPATH_GET_SEPARATOR );
	wxString backupName = path + _T("VVV.fbk");
	if( !wxFileExists(backupName) ) {
		CUtils::MsgErr( _("Unable to find the database backup to restore.\n\nYou can try reinstalling the program to solve this problem.") );
		return;
	}

	wxBusyCursor wait;
	
	// restore the database
	CBaseDB::CreateFirebirdDatabaseOnDisk( "", "SYSDBA", "masterkey", backupName, databaseFile );
	
	// since under Windows the restore process creates an all-uppercase file name, rename it to the original name
#ifdef __WXMSW__
	{
		wxFileName fn(databaseFile);
		wxString name = fn.GetFullName();
		wxString path = fn.GetPath( wxPATH_GET_VOLUME | wxPATH_GET_SEPARATOR );
		wxString ucDatabaseFile = path + name.Upper();
		wxString tmpDatabaseFile = ucDatabaseFile + "$$tmp$$";
		if( wxFileExists(tmpDatabaseFile) )
			wxRemoveFile( tmpDatabaseFile );
		wxRenameFile( ucDatabaseFile, tmpDatabaseFile, false );
		wxRenameFile( tmpDatabaseFile, databaseFile, false );
	}
#endif

	// open the database
	OpenDatabase( databaseFile, CUtils::GetExpectedDatabaseVersion() );

}

/*!
 * wxEVT_COMMAND_MENU_SELECTED event handler for ID_EDIT_VOLUME_DESCRIPTION
 */

void CMainFrame::OnEditVolumeDescriptionClick( wxCommandEvent& WXUNUSED(event) )
{
	wxTreeCtrl *tctl = GetTreePhysicalControl();
	wxTreeItemId item = tctl->GetSelection();
	wxString volumeName = tctl->GetItemText( item );
    MyTreeItemData *itemData = (MyTreeItemData *) tctl->GetItemData(item);

	CDialogVolumeDescription dialog( this, ID_DIALOG_VOLUME_DESCRIPTION, _("Volume description") );
	dialog.SetVolumeName( volumeName );
	wxString orgDescr = itemData->GetVolumeDescription();
	dialog.SetDescription( orgDescr );

	if( dialog.ShowModal() != wxID_OK ) return;

	wxString newDescr = dialog.GetDescription();
	if( newDescr == orgDescr) return;

	CVolumes vol;
	vol.VolumeID = itemData->GetVolumeID();
	vol.VolumeName = itemData->GetDesc();
	vol.VolumeDescription = newDescr;
	vol.DbUpdate();

	itemData->SetVolumeDescription( newDescr );

	// updates the tree control
	tctl->SetItemText( item, CreateVolumeLabel(vol.VolumeName, newDescr) );

}

/*!
 * wxEVT_UPDATE_UI event handler for ID_EDIT_VOLUME_DESCRIPTION
 */

void CMainFrame::OnEditVolumeDescriptionUpdate( wxUpdateUIEvent& event )
{
	if( CBaseDB::GetDatabase() == NULL || m_CurrentView != Physical ) {
		event.Enable(false);
		return;
	}
	
	bool hideElement = false;
	wxTreeCtrl *tctl = GetTreePhysicalControl();
	if( tctl->GetCount() > 0 ) {
		wxTreeItemId item = tctl->GetSelection();
		if( item.IsOk() ) {
			if( tctl->GetItemParent(item) != tctl->GetRootItem() ) hideElement = true;
		}
		else {
			hideElement = true;
		}
	}
	else
		hideElement = true;

	event.Enable( !hideElement );
}

wxString CMainFrame::CreateVolumeLabel( const wxString& VolumeName, const wxString& VolumeDescription ) {
	wxString retVal;

	retVal = VolumeName;
	if( !VolumeDescription.empty() ) {
		wxString s = VolumeDescription.Left(20);
		s.Replace( "\n", " " );
		retVal += " - " + s;
	}
	return retVal;
}

/*!
 * wxEVT_COMMAND_TREE_ITEM_MENU event handler for ID_TREE_CONTROL
 */

void CMainFrame::OnTreeControlItemMenu( wxTreeEvent& event )
{
	wxTreeItemId item = event.GetItem();
	if( !item.IsOk() ) return;

	wxTreeCtrl *tctl = GetTreePhysicalControl();
	tctl->SelectItem( item );
	
    wxPoint pt = event.GetPoint();
    // if there is a toolbar we need to correct the coordinates
	wxPoint origin = GetClientAreaOrigin();
    pt += origin;

	wxMenu menu;
	menu.Append( ID_ADD_VIRTUAL_FOLDER, _("Add To Virtual Folder") );
	if( tctl->GetItemParent(item) == tctl->GetRootItem() ) {
		// only for voume nodes, not for folders
	    menu.AppendSeparator();
		menu.Append( ID_EDIT_VOLUME_DESCRIPTION, _("Edit description") );
		menu.Append( ID_RENAME_VOLUME, _("Rename") );
		menu.Append( ID_DELETE_VOLUME, _("Delete") );
	}

	PopupMenu( &menu, pt );

	event.Skip();
}



void CMainFrame::OnTreeControlVirtualItemMenu( wxTreeEvent& event )
{
	wxTreeItemId item = event.GetItem();
//	if( !item.IsOk() ) return;

	wxTreeCtrl *tctl = GetTreeVirtualControl();
	if( item.IsOk() ) tctl->SelectItem( item );
	
    wxPoint pt = event.GetPoint();
    // if there is a toolbar we need to correct the coordinates
	wxPoint origin = GetClientAreaOrigin();
    pt += origin;

	wxMenu menu;
	menu.Append( ID_NEW_VIRTUAL_ROOT_FOLDER, _("New Root Folder") );
	if( item.IsOk() ) {
		// only if we have a selected item
		menu.Append( ID_NEW_VIRTUAL_SUBFOLDER, _("New Subfolder") );
	    MyTreeItemData *itemData = (MyTreeItemData *) tctl->GetItemData(item);
		if( itemData->GetPhysPathID().IsNull() ) menu.Append( ID_RENAME_VIRTUAL_FOLDER, _("Rename") );
		menu.Append( ID_DELETE_VIRTUAL_FOLDER, _("Delete") );
	}

	PopupMenu( &menu, pt );

	event.Skip();
}

/*!
 * wxEVT_COMMAND_MENU_SELECTED event handler for ID_VIEW_SEARCH
 */

void CMainFrame::OnViewSearchClick( wxCommandEvent& event )
{
	if( !event.IsChecked() ) return;
	if( m_CurrentView == Search ) return;

	wxSplitterWindow* sw = GetSplitterWindow();
	long sp = sw->GetSashPosition();
	wxListCtrl* lctl = GetListControl();
	sw->Unsplit();
	switch( m_CurrentView ) {
		case Physical:
			HidePhysicalView();
			break;
		case Virtual:
			HideVirtualView();
			break;
		default:
			wxASSERT(true);
	}
	ShowSearchView();
	sw->SplitVertically( m_SearchPanel, lctl );
	sw->SetSashPosition( sp );
	DeleteAllListControlItems();

	nSearchFiles = 0;
	sizeSearchFiles = 0;
	UpdateStatusBar( nSearchFiles, sizeSearchFiles );
}

/*!
 * wxEVT_UPDATE_UI event handler for ID_VIEW_SEARCH
 */

void CMainFrame::OnViewSearchUpdate( wxUpdateUIEvent& event )
{
	event.Enable( CBaseDB::GetDatabase() != NULL );
	
	if( m_CurrentView == Search )
		event.Check(true);
	else
		event.Check(false);
}

void CMainFrame::ShowPhysicalView(void) {
	wxTreeCtrl* tctlPhysical = GetTreePhysicalControl();
	tctlPhysical->Show( true );
	m_CurrentView = Physical;
	CreateListControlHeaders();
	ShowSelectedFolderFiles();
}

void CMainFrame::HidePhysicalView(void) {
	StoreListControlPhysicalWidth();
	wxTreeCtrl* tctlPhysical = GetTreePhysicalControl();
	tctlPhysical->Show( false );

}

void CMainFrame::ShowVirtualView(void) {
	wxTreeCtrl* tctlVirtual = GetTreeVirtualControl();
	tctlVirtual->Show( true );
	m_CurrentView = Virtual;
	CreateListControlHeaders();
	ShowSelectedVirtualFolderFiles();

}

void CMainFrame::HideVirtualView(void) {
	StoreListControlVirtualWidth();
	wxTreeCtrl* tctlVirtual = GetTreeVirtualControl();
	tctlVirtual->Show( false );

}

void CMainFrame::ShowSearchView(void) {
	m_SearchPanel->Show( true );
	m_CurrentView = Search;
	CreateListControlHeaders();

	// checks if there is a selected item in the tree controls and enables/disables the radio buttons
	// physical...
	wxTreeCtrl *tctl = GetTreePhysicalControl();
	bool isFolderSelected = false;	// true if the selected item is a volume
	if( tctl->GetCount() > 0 ) {
		wxTreeItemId item = tctl->GetSelection();
		if( item.IsOk() ) {
			isFolderSelected = true;
		}
	}
	m_SearchRadioBox->Enable( SelectedPhysicalFolder, isFolderSelected );
	// virtual...
	tctl = GetTreeVirtualControl();
	isFolderSelected = false;	// true if the selected item is a volume
	if( tctl->GetCount() > 0 ) {
		wxTreeItemId item = tctl->GetSelection();
		if( item.IsOk() ) {
			isFolderSelected = true;
		}
	}
	m_SearchRadioBox->Enable( SelectedVirtualFolder, isFolderSelected );

}

void CMainFrame::HideSearchView(void) {
	m_SearchPanel->Show( false );
}

void CMainFrame::OnButtonSearchClick( wxCommandEvent& WXUNUSED(event) ) {
	bool useWildcards;

	wxString fileName = m_SearchFileName->GetValue();
	wxString ext = m_SearchExtension->GetValue();

	if( fileName.empty() && ext.empty() ) {
		CUtils::MsgErr( _("Please enter a file name or extension") );
		return;
	}

	// escapes wildcards chars typed by the user
	FilenameSearchKind searchKind = (FilenameSearchKind) m_FilenameRadioBox->GetSelection();
	useWildcards = false;
	if( !fileName.empty() ) {
		switch( searchKind ) {
			case StartsWith:
				useWildcards = true;
				fileName = CBaseRec::EscapeWildcards( fileName, "/" );
				fileName = fileName + "%";
				break;
			case Contains:
				useWildcards = true;
				fileName = CBaseRec::EscapeWildcards( fileName, "/" );
				fileName = "%" + fileName + "%";
				break;
		}
	}

	SearchScope scope = (SearchScope) m_SearchRadioBox->GetSelection();
	wxBusyCursor wait;
	wxListCtrl* lctl = GetListControl();
	
	// assigns the image list
	wxImageList* iml = new wxImageList( 16, 16 );
	iml->Add(wxIcon(folder_closed_xpm));
	iml->Add(wxIcon(deffile_xpm));
	lctl->AssignImageList( iml, wxIMAGE_LIST_SMALL );

	nSearchFiles = 0;
	sizeSearchFiles = 0;

	DeleteAllListControlItems();
	lctl->Hide();	// to speed up things

	switch( scope ) {
		case AllPhysicalVolumes : {
			CFiles files;
			CNullableLong nl;
			nl.SetNull(true);
			files.DBStartSearchVolumeFiles( fileName, useWildcards, ext, nl );
			while( !files.IsEOF() ) {
				AddRowToVirtualListControl( lctl, files.IsFolder(), files.FileName, files.FileSize, files.FileExt, files.DateTime, CPaths::GetFullPath(files.PathID), files.PathFileID.IsNull() ? 0 : (long) files.PathFileID );
				nSearchFiles++;
				sizeSearchFiles += files.FileSize;
				files.DBNextRow();
			}
			break;
		}
		case SelectedPhysicalFolder: {
			wxTreeCtrl *tctl = GetTreePhysicalControl();
			wxASSERT( tctl->GetCount() > 0 );
			wxTreeItemId item = tctl->GetSelection();
			wxASSERT( item.IsOk() );
		    MyTreeItemData *itemData = (MyTreeItemData *) tctl->GetItemData(item);

			if( tctl->GetItemParent(item) == tctl->GetRootItem() ) {
				// the user selected a volume
				CFiles files;
				files.DBStartSearchVolumeFiles( fileName, useWildcards, ext, itemData->GetVolumeID() );
				while( !files.IsEOF() ) {
					AddRowToVirtualListControl( lctl, files.IsFolder(), files.FileName, files.FileSize, files.FileExt, files.DateTime, CPaths::GetFullPath(files.PathID), files.PathFileID.IsNull() ? 0 : (long) files.PathFileID );
					nSearchFiles++;
					sizeSearchFiles += files.FileSize;
					files.DBNextRow();
				}
			}
			else {
				// the user selected a folder: recursion
				CBaseDB::GetDatabase()->TransactionStart( true );
				SearchPhysicalFolder( fileName, useWildcards, ext, itemData->GetPathID(), itemData->GetVolumeID() );
				CBaseDB::GetDatabase()->TransactionCommit();
			}
			break;
		}
		case SelectedVirtualFolder: {
			wxTreeCtrl *tctl = GetTreeVirtualControl();
			wxASSERT( tctl->GetCount() > 0 );
			wxTreeItemId item = tctl->GetSelection();
			wxASSERT( item.IsOk() );
		    MyTreeItemData *itemData = (MyTreeItemData *) tctl->GetItemData(item);
			CBaseDB::GetDatabase()->TransactionStart( true );
			SearchVirtualFolder( fileName, useWildcards, ext, itemData->GetPathID() );
			CBaseDB::GetDatabase()->TransactionCommit();
			break;
		}
		default:
			wxASSERT( true );
			break;
	}

	lctl->SortItems( ListControlCompareFunction, 0 );
	lctl->Show();

	UpdateStatusBar( nSearchFiles, sizeSearchFiles );
}

int CMainFrame::AddRowToVirtualListControl( wxListCtrl* lctl, bool isFolder, wxString fileName, wxLongLong fileSize, wxString ext, wxDateTime dateTime, wxString physicalPath, long virtualPathFileID ) {
	int imageIndex = (isFolder ? 0 : 1 );
	wxListItem item;
	item.SetMask( wxLIST_MASK_STATE|wxLIST_MASK_TEXT|wxLIST_MASK_IMAGE|wxLIST_MASK_DATA );
	int i = lctl->InsertItem( item );
	lctl->SetItem( i, 0, fileName, imageIndex );
	lctl->SetItem( i, 1, isFolder ? "" : CUtils::HumanReadableFileSize(fileSize) );
	lctl->SetItem( i, 2, ext );
	lctl->SetItem( i, 3, dateTime.FormatDate() + " " + dateTime.FormatTime() );
	lctl->SetItem( i, 4, physicalPath );
	lctl->SetItemData( i, (long) new MyListItemData( virtualPathFileID, fileName, ext, fileSize, dateTime, isFolder, physicalPath ) );
	if( physicalPath.empty() ) lctl->SetItemTextColour( i, *wxBLUE );

	return i;
}

void CMainFrame::SearchVirtualFolder( wxString fileName, bool useFileNameWildcards, wxString ext, long folderID ) {

	// searches the current folder
	CVirtualFiles files;
	wxListCtrl* lctl = GetListControl();
	files.DBStartSearchFolderFiles( fileName, useFileNameWildcards, ext, folderID );
	while( !files.IsEOF() ) {
		AddRowToVirtualListControl( lctl, files.IsFolder(), files.FileName, files.FileSize, files.FileExt, files.DateTime, files.FullPhysicalPath, files.VirtualPathFileID.IsNull() ? 0 : (long) files.VirtualPathFileID );
		nSearchFiles++;
		sizeSearchFiles += files.FileSize;
		files.DBNextRow();
	}

	// recursion in the subfolders
	CVirtualPaths pth;
	pth.DBStartQueryListPaths( folderID );
	while( !pth.IsEOF() ) {
		SearchVirtualFolder( fileName, useFileNameWildcards, ext, pth.PathID );
		pth.DBNextRow();
	}

}

void CMainFrame::SearchPhysicalFolder( wxString fileName, bool useFileNameWildcards, wxString ext, long folderID, long volumeID ) {

	// searches the current folder
	CFiles files;
	wxListCtrl* lctl = GetListControl();
	files.DBStartSearchFolderFiles( fileName, useFileNameWildcards, ext, folderID );
	while( !files.IsEOF() ) {
		AddRowToVirtualListControl( lctl, files.IsFolder(), files.FileName, files.FileSize, files.FileExt, files.DateTime, CPaths::GetFullPath(files.PathID), files.PathFileID.IsNull() ? 0 : (long) files.PathFileID );
		nSearchFiles++;
		sizeSearchFiles += files.FileSize;
		files.DBNextRow();
	}

	// recursion in the subfolders
	CPaths pth;
	pth.DBStartQueryListPaths( volumeID, folderID );
	while( !pth.IsEOF() ) {
		SearchPhysicalFolder( fileName, useFileNameWildcards, ext, pth.PathID, volumeID );
		pth.DBNextRow();
	}

}


/*!
 * wxEVT_COMMAND_LIST_ITEM_ACTIVATED event handler for ID_LIST_CONTROL
 */

void CMainFrame::OnListControlItemActivated( wxListEvent& event )
{
	int i = event.GetIndex();
	wxListCtrl* lctl = GetListControl();
	MyListItemData *itemData = (MyListItemData *) lctl->GetItemData( i );

	if( !itemData->IsFolder() ) return;
	long pathFileID = itemData->GetPathFileID();
	if( pathFileID == 0 ) return;

	wxTreeCtrl *tctl = NULL;
	switch( m_CurrentView ) {
		case Physical:
			tctl = GetTreePhysicalControl();
			break;
		case Virtual:
			tctl = GetTreeVirtualControl();
			break;
		default:
			wxASSERT( true );
	}
	// this is the selected item in the tree control
	wxTreeItemId itemFather = tctl->GetSelection();

	// looks for the child corresponding to the folder in the list view
	wxTreeItemIdValue cookie;
	wxTreeItemId itemChild = tctl->GetFirstChild( itemFather, cookie );
	while( itemChild.IsOk() ) {
		MyTreeItemData *tid = (MyTreeItemData *) tctl->GetItemData(itemChild);
		if( tid->GetPathID() == pathFileID ) {
			tctl->SelectItem( itemChild );
			break;
		}
		itemChild = tctl->GetNextChild( itemFather, cookie );
	}

}

void CMainFrame::UpdateStatusBar( long nObjects, wxLongLong sizeObjects ) {

	if( nObjects == 0 )
		m_StatusBar->SetStatusText( "", ObjectsNumber );
	else {
		wxString s = _("Objects: ") + CUtils::long2string( nObjects );
		m_StatusBar->SetStatusText( s, ObjectsNumber );
	}

	if( sizeObjects == 0 )
		m_StatusBar->SetStatusText( "", ObjectsSize );
	else {
		wxString s = _("Total size: ") + CUtils::HumanReadableFileSize( sizeObjects );
		m_StatusBar->SetStatusText( s, ObjectsSize );
	}

}


/*!
 * wxEVT_COMMAND_MENU_SELECTED event handler for ID_VIEW_STATUS_BAR
 */

void CMainFrame::OnViewStatusBarClick( wxCommandEvent& event )
{
	if( event.IsChecked() )
		GetStatusBar()->Show(true);
	else {
		GetStatusBar()->Show(false);
	}

#ifdef __WXMSW__
	SendSizeEvent();
#else
	wxSize s = GetSize();
	Fit();
	SetSize(s);
#endif
}

/*!
 * wxEVT_COMMAND_MENU_SELECTED event handler for ID_UP_ONE_FOLDER
 */

void CMainFrame::OnUpOneFolderClick( wxCommandEvent& WXUNUSED(event) )
{
	wxTreeCtrl *tctl = (m_CurrentView == Physical) ? GetTreePhysicalControl() : GetTreeVirtualControl();
	wxTreeItemId item = tctl->GetSelection();
	tctl->SelectItem( tctl->GetItemParent(item) );
}

/*!
 * wxEVT_UPDATE_UI event handler for ID_UP_ONE_FOLDER
 */

void CMainFrame::OnUpOneFolderUpdate( wxUpdateUIEvent& event )
{
	if( CBaseDB::GetDatabase() == NULL || m_CurrentView == Search ) {
		event.Enable(false);
		return;
	}
	
	bool hideElement = true;
	wxTreeCtrl *tctl = m_CurrentView == Physical ? GetTreePhysicalControl() : GetTreeVirtualControl();
	if( tctl->GetCount() > 0 ) {
		wxTreeItemId item = tctl->GetSelection();
		if( item.IsOk() ) {
			if( tctl->GetItemParent(item) != tctl->GetRootItem() ) hideElement = false;
		}
	}

	event.Enable( !hideElement );
}

